import MathematicalCommons.Noether.PolynomialIdealsAndResultants1923.RegularTailDisjoint
import Mathlib.LinearAlgebra.Projection
import Mathlib.RingTheory.Polynomial.DegreeLT

/-!
# Hentzelt--Noether equation (21): the finite quotient by a regular polynomial

Module for P22, controlled witness `NOETH-DE-ED-0014`, SHA-256
`EE226847656BC4D65EDDA9E9BF9BB1D25797C0C6D672D267D94A97FD88C7AD58`,
lines 13134--13160. Regular division gives representatives of first-variable
degree below `k`; equations (22)--(23) then use their `k` coefficients as the
finite variables of the next module. This file packages the exact linear
consequence: the polynomial module modulo the principal tail generated by a
regular polynomial is free finite on those `k` coefficient classes.

The base ring is the polynomial ring in the remaining variables. No
Noetherianity or finite-dimensionality over the original field is asserted.
-/

namespace MathematicalCommons.Noether.PolynomialIdealsAndResultants1923

open MvPolynomial
open RegularitySpecialization
open RegularityDivision
open Module

namespace RegularIdealDecomposition

noncomputable section

variable {P : Type*} [Field P]
variable {n k : ℕ}

/-- For the unit ideal, the bounded part is exactly the module of polynomials
of degree strictly below `k`. -/
@[simp]
theorem boundedPart_top (k : ℕ) :
    boundedPart
        (⊤ : Ideal (Polynomial (MvPolynomial (Fin n) P))) k =
      Polynomial.degreeLT (MvPolynomial (Fin n) P) k := by
  simp [boundedPart]

/-- The degree-bounded representatives are disjoint from the principal tail
of a regular polynomial. -/
theorem degreeLT_disjoint_principalTail
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    Disjoint (Polynomial.degreeLT (MvPolynomial (Fin n) P) k)
      (principalTail C) := by
  simpa only [boundedPart_top] using
    boundedPart_disjoint_principalTail
      (⊤ : Ideal (Polynomial (MvPolynomial (Fin n) P))) C hC

/-- Regular division says that the bounded representatives and principal tail
span the whole polynomial module. -/
theorem degreeLT_sup_principalTail_eq_top
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    Polynomial.degreeLT (MvPolynomial (Fin n) P) k ⊔ principalTail C = ⊤ := by
  have h := regularIdeal_eq_boundedPart_sup_principalTail
    (⊤ : Ideal (Polynomial (MvPolynomial (Fin n) P))) C hC (by simp)
  simpa [boundedPart] using h.symm

/-- The principal tail and the `k`-coefficient representative module are
complements. This is the module-theoretic form of the representative-system
claim immediately after equation (21). -/
theorem principalTail_isCompl_degreeLT
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    IsCompl (principalTail C)
      (Polynomial.degreeLT (MvPolynomial (Fin n) P) k) := by
  refine ⟨(degreeLT_disjoint_principalTail C hC).symm, ?_⟩
  apply codisjoint_iff.mpr
  simpa [sup_comm] using degreeLT_sup_principalTail_eq_top C hC

/-- Every residue class modulo the principal tail of a regular polynomial has
a unique representative of first-variable degree below `k`. -/
noncomputable def quotientByRegularEquivDegreeLT
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    (Polynomial (MvPolynomial (Fin n) P) ⧸ principalTail C) ≃ₗ[
      MvPolynomial (Fin n) P]
      Polynomial.degreeLT (MvPolynomial (Fin n) P) k :=
  (principalTail C).quotientEquivOfIsCompl
    (Polynomial.degreeLT (MvPolynomial (Fin n) P) k)
    (principalTail_isCompl_degreeLT C hC)

/-- A bounded representative is fixed by the quotient-to-remainder
equivalence. -/
@[simp]
theorem quotientByRegularEquivDegreeLT_apply_mk
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C)
    (r : Polynomial.degreeLT (MvPolynomial (Fin n) P) k) :
    quotientByRegularEquivDegreeLT C hC
        (Submodule.Quotient.mk
          (r : Polynomial (MvPolynomial (Fin n) P))) = r := by
  exact Submodule.quotientEquivOfIsCompl_apply_mk_right
    (principalTail_isCompl_degreeLT C hC) r

/-- Coefficient-vector form of the finite representative system following
equation (21). -/
noncomputable def quotientByRegularEquivCoefficients
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    (Polynomial (MvPolynomial (Fin n) P) ⧸ principalTail C) ≃ₗ[
      MvPolynomial (Fin n) P]
      (Fin k → MvPolynomial (Fin n) P) :=
  (quotientByRegularEquivDegreeLT C hC).trans
    (Polynomial.degreeLTEquiv (MvPolynomial (Fin n) P) k)

/-- The `k` coefficient classes form a basis of the quotient by the regular
principal tail. -/
noncomputable def quotientByRegularBasis
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    Basis (Fin k) (MvPolynomial (Fin n) P)
      (Polynomial (MvPolynomial (Fin n) P) ⧸ principalTail C) :=
  Basis.ofEquivFun (quotientByRegularEquivCoefficients C hC)

/-- The quotient by the regular principal tail is a finite module over the
remaining-variable coefficient ring. -/
theorem quotientByRegular_moduleFinite
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    Module.Finite (MvPolynomial (Fin n) P)
      (Polynomial (MvPolynomial (Fin n) P) ⧸ principalTail C) :=
  Module.Finite.of_basis (quotientByRegularBasis C hC)

/-- The same quotient is free, with rank indexed by the `k` bounded
coefficients. -/
theorem quotientByRegular_moduleFree
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    Module.Free (MvPolynomial (Fin n) P)
      (Polynomial (MvPolynomial (Fin n) P) ⧸ principalTail C) :=
  Module.Free.of_basis (quotientByRegularBasis C hC)

/-- The principal tail lies in every ideal containing its regular generator. -/
theorem principalTail_le_restrictScalars
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C : MvPolynomial (Fin (n + 1)) P)
    (hCI : MvPolynomial.finSuccEquiv P n C ∈ I) :
    principalTail C ≤ I.restrictScalars (MvPolynomial (Fin n) P) := by
  intro H hH
  change H ∈ I
  change H ∈ Ideal.span ({MvPolynomial.finSuccEquiv P n C} :
    Set (Polynomial (MvPolynomial (Fin n) P))) at hH
  exact (Ideal.span_le.mpr (by simpa using hCI)) hH

/-- The bounded coefficient module of an ideal, viewed inside the canonical
degree-`< k` representative module. -/
def boundedPartInDegreeLT
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P))) (k : ℕ) :
    Submodule (MvPolynomial (Fin n) P)
      (Polynomial.degreeLT (MvPolynomial (Fin n) P) k) :=
  (I.restrictScalars (MvPolynomial (Fin n) P)).comap
    (Polynomial.degreeLT (MvPolynomial (Fin n) P) k).subtype

@[simp]
theorem mem_boundedPartInDegreeLT_iff
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (r : Polynomial.degreeLT (MvPolynomial (Fin n) P) k) :
    r ∈ boundedPartInDegreeLT I k ↔
      (r : Polynomial (MvPolynomial (Fin n) P)) ∈ I := by
  rfl

/-- The image of an ideal in the quotient by the regular principal tail. -/
def idealImageInRegularQuotient
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C : MvPolynomial (Fin (n + 1)) P) :
    Submodule (MvPolynomial (Fin n) P)
      (Polynomial (MvPolynomial (Fin n) P) ⧸ principalTail C) :=
  (I.restrictScalars (MvPolynomial (Fin n) P)).map
    (principalTail C).mkQ

/-- Under the canonical regular-remainder equivalence, the image of an ideal
containing `C` is exactly its bounded coefficient module. This is the precise
finite-module content used to pass from equation (23) to Satz VII. -/
theorem map_idealImageInRegularQuotient_eq_boundedPartInDegreeLT
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C)
    (hCI : MvPolynomial.finSuccEquiv P n C ∈ I) :
    (idealImageInRegularQuotient I C).map
        (quotientByRegularEquivDegreeLT C hC :
          (Polynomial (MvPolynomial (Fin n) P) ⧸ principalTail C) →ₗ[
            MvPolynomial (Fin n) P]
          Polynomial.degreeLT (MvPolynomial (Fin n) P) k) =
      boundedPartInDegreeLT I k := by
  apply le_antisymm
  · intro r hr
    rcases hr with ⟨z, hz, hzr⟩
    rcases hz with ⟨H, hHI, hHz⟩
    subst z
    subst r
    change (quotientByRegularEquivDegreeLT C hC
      (Submodule.Quotient.mk H) :
        Polynomial (MvPolynomial (Fin n) P)) ∈ I
    have hdiff :
        H - (quotientByRegularEquivDegreeLT C hC
          (Submodule.Quotient.mk H) :
            Polynomial (MvPolynomial (Fin n) P)) ∈ principalTail C := by
      rw [quotientByRegularEquivDegreeLT,
        Submodule.quotientEquivOfIsCompl_apply_mk]
      exact Submodule.sub_projection_mem
        (principalTail_isCompl_degreeLT C hC).symm H
    have hdiffI :
        H - (quotientByRegularEquivDegreeLT C hC
          (Submodule.Quotient.mk H) :
            Polynomial (MvPolynomial (Fin n) P)) ∈ I :=
      principalTail_le_restrictScalars I C hCI hdiff
    change H ∈ I at hHI
    have hrem := I.sub_mem hHI hdiffI
    simpa only [sub_sub_cancel] using hrem
  · intro r hr
    refine ⟨Submodule.Quotient.mk
      (r : Polynomial (MvPolynomial (Fin n) P)), ?_, ?_⟩
    · refine ⟨(r : Polynomial (MvPolynomial (Fin n) P)), ?_, rfl⟩
      exact hr
    · exact quotientByRegularEquivDegreeLT_apply_mk C hC r

/-- The preceding image equality as a linear equivalence of the two finite
coefficient modules. -/
noncomputable def regularIdealImageEquivBoundedPart
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C)
    (hCI : MvPolynomial.finSuccEquiv P n C ∈ I) :
    idealImageInRegularQuotient I C ≃ₗ[MvPolynomial (Fin n) P]
      boundedPartInDegreeLT I k :=
  (quotientByRegularEquivDegreeLT C hC).ofSubmodules
    (idealImageInRegularQuotient I C) (boundedPartInDegreeLT I k)
    (map_idealImageInRegularQuotient_eq_boundedPartInDegreeLT I C hC hCI)

#print axioms boundedPart_top
#print axioms degreeLT_disjoint_principalTail
#print axioms degreeLT_sup_principalTail_eq_top
#print axioms principalTail_isCompl_degreeLT
#print axioms quotientByRegularEquivDegreeLT
#print axioms quotientByRegularEquivDegreeLT_apply_mk
#print axioms quotientByRegularEquivCoefficients
#print axioms quotientByRegularBasis
#print axioms quotientByRegular_moduleFinite
#print axioms quotientByRegular_moduleFree
#print axioms principalTail_le_restrictScalars
#print axioms boundedPartInDegreeLT
#print axioms mem_boundedPartInDegreeLT_iff
#print axioms idealImageInRegularQuotient
#print axioms map_idealImageInRegularQuotient_eq_boundedPartInDegreeLT
#print axioms regularIdealImageEquivBoundedPart

end

end RegularIdealDecomposition

end MathematicalCommons.Noether.PolynomialIdealsAndResultants1923
