import MathematicalCommons.Noether.PolynomialIdealsAndResultants1923.RegularIdealDecomposition

/-!
# Hentzelt--Noether equation (23): directness of the regular decomposition

Module for P22, controlled witness `NOETH-DE-ED-0014`, SHA-256
`EE226847656BC4D65EDDA9E9BF9BB1D25797C0C6D672D267D94A97FD88C7AD58`,
lines 13149--13160. The bounded part and the tail generated by a polynomial
regular of first-variable degree `k` have zero intersection. Thus the sum in
equation (23) is internal, not merely a spanning statement.
-/

namespace MathematicalCommons.Noether.PolynomialIdealsAndResultants1923

open MvPolynomial
open RegularitySpecialization
open RegularityDivision

namespace RegularIdealDecomposition

noncomputable section

variable {P : Type*} [Field P]
variable {n k : ℕ}

/-- The principal tail generated by the monic normalization of the regular
polynomial. This auxiliary form exposes the degree argument used to prove
directness. -/
def monicPrincipalTail
    (C : MvPolynomial (Fin (n + 1)) P) (k : ℕ) :
    Submodule (MvPolynomial (Fin n) P)
      (Polynomial (MvPolynomial (Fin n) P)) :=
  (Ideal.span ({monicRegularDivisor C k} :
    Set (Polynomial (MvPolynomial (Fin n) P)))).restrictScalars
      (MvPolynomial (Fin n) P)

/-- Multiplying a regular divisor by the inverse of its nonzero pure-power
coefficient does not change its principal ideal. This makes explicit that
Noether's original tail and the monic tail used by polynomial division are
the same submodule. -/
theorem principalTail_eq_monicPrincipalTail
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    principalTail C = monicPrincipalTail C k := by
  let c : P := MvPolynomial.coeff
    (Finsupp.single (0 : Fin (n + 1)) k) C
  have hc : c ≠ 0 := hC.2
  have hu : IsUnit
      (Polynomial.C (MvPolynomial.C c⁻¹) :
        Polynomial (MvPolynomial (Fin n) P)) :=
    (((isUnit_iff_ne_zero.mpr (inv_ne_zero hc)).map MvPolynomial.C).map
      Polynomial.C)
  have hspan :
      Ideal.span ({monicRegularDivisor C k} :
          Set (Polynomial (MvPolynomial (Fin n) P))) =
        Ideal.span ({MvPolynomial.finSuccEquiv P n C} :
          Set (Polynomial (MvPolynomial (Fin n) P))) := by
    simpa [monicRegularDivisor, c] using
      (Ideal.span_singleton_mul_left_unit hu
        (MvPolynomial.finSuccEquiv P n C))
  exact congrArg
    (fun J : Ideal (Polynomial (MvPolynomial (Fin n) P)) ↦
      J.restrictScalars (MvPolynomial (Fin n) P)) hspan.symm

/-- Source-critical directness assertion for P22 lines 13149--13160: no
nonzero polynomial can simultaneously have first-variable degree below `k`
and be a multiple of a polynomial regular of first-variable degree `k`.

The ideal `I` is arbitrary; only its bounded part enters the intersection.
-/
theorem boundedPart_disjoint_principalTail
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    Disjoint (boundedPart I k) (principalTail C) := by
  refine Submodule.disjoint_def.mpr fun H hbounded htail ↦ ?_
  rw [principalTail_eq_monicPrincipalTail C hC] at htail
  change H ∈ Ideal.span ({monicRegularDivisor C k} :
    Set (Polynomial (MvPolynomial (Fin n) P))) at htail
  have hdvd : monicRegularDivisor C k ∣ H :=
    Ideal.mem_span_singleton.mp htail
  apply Polynomial.eq_zero_of_dvd_of_degree_lt hdvd
  have hmonic := monic_monicRegularDivisor C hC
  rw [Polynomial.degree_eq_natDegree hmonic.ne_zero,
    natDegree_monicRegularDivisor C hC]
  exact Polynomial.mem_degreeLT.mp hbounded.2

/-- Intersection form of `boundedPart_disjoint_principalTail`. -/
theorem boundedPart_inf_principalTail_eq_bot
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    boundedPart I k ⊓ principalTail C = ⊥ :=
  (boundedPart_disjoint_principalTail I C hC).eq_bot

/-- Equation (23) strengthened to an internal sum: when `I` contains the
regular polynomial, its bounded part and principal tail both span `I` and
have zero intersection. -/
theorem regularIdeal_eq_internal_sup
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C)
    (hCI : MvPolynomial.finSuccEquiv P n C ∈ I) :
    I.restrictScalars (MvPolynomial (Fin n) P) =
        boundedPart I k ⊔ principalTail C ∧
      boundedPart I k ⊓ principalTail C = ⊥ :=
  ⟨regularIdeal_eq_boundedPart_sup_principalTail I C hC hCI,
    boundedPart_inf_principalTail_eq_bot I C hC⟩

#print axioms monicPrincipalTail
#print axioms principalTail_eq_monicPrincipalTail
#print axioms boundedPart_disjoint_principalTail
#print axioms boundedPart_inf_principalTail_eq_bot
#print axioms regularIdeal_eq_internal_sup

end

end RegularIdealDecomposition

end MathematicalCommons.Noether.PolynomialIdealsAndResultants1923
