import MathematicalCommons.Noether.PolynomialIdealsAndResultants1923.RegularityDivision
import Mathlib.Algebra.Polynomial.RingDivision
import Mathlib.RingTheory.Polynomial.Basic

/-!
# Hentzelt--Noether equations (22)--(23): bounded ideal representatives

Module for P22, controlled witness `NOETH-DE-ED-0014`, SHA-256
`EE226847656BC4D65EDDA9E9BF9BB1D25797C0C6D672D267D94A97FD88C7AD58`,
lines 13141--13158. Equation (22) records the finitely many coefficients of
the remainder supplied by regular division. Equation (23) decomposes an ideal
containing the regular polynomial into its bounded-remainder part and the
principal tail generated by that polynomial.

The decomposition is over the coefficient ring in the remaining variables.
It does not assert that the whole ideal is a finite module over that ring: the
principal tail contains all powers `X ^ nu * C`.
-/

namespace MathematicalCommons.Noether.PolynomialIdealsAndResultants1923

open MvPolynomial
open RegularitySpecialization
open RegularityDivision

namespace RegularIdealDecomposition

noncomputable section

variable {P : Type*} [Field P]
variable {n k : ℕ}

/-- The part of an ideal represented by polynomials of first-variable degree
strictly less than `k`. This is Noether's finite-variable module `M₁*` (or
`G₁*`) in the univariate-over-the-remaining-variables presentation. -/
def boundedPart
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P))) (k : ℕ) :
    Submodule (MvPolynomial (Fin n) P)
      (Polynomial (MvPolynomial (Fin n) P)) :=
  I.restrictScalars (MvPolynomial (Fin n) P) ⊓
    Polynomial.degreeLT (MvPolynomial (Fin n) P) k

/-- The `R`-module underlying the principal ideal generated by the regular
polynomial. Its generators are the infinite family `X ^ ν * C` from P22. -/
def principalTail
    (C : MvPolynomial (Fin (n + 1)) P) :
    Submodule (MvPolynomial (Fin n) P)
      (Polynomial (MvPolynomial (Fin n) P)) :=
  (Ideal.span {MvPolynomial.finSuccEquiv P n C}).restrictScalars
    (MvPolynomial (Fin n) P)

/-- If an ideal contains both the regular divisor and `H`, then it contains
the regular remainder of `H`. -/
theorem regularRemainder_mem_ideal
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C H : MvPolynomial (Fin (n + 1)) P) (k : ℕ)
    (hCI : MvPolynomial.finSuccEquiv P n C ∈ I)
    (hHI : MvPolynomial.finSuccEquiv P n H ∈ I) :
    regularRemainder C k H ∈ I := by
  have hmul : MvPolynomial.finSuccEquiv P n C * regularQuotient C k H ∈ I :=
    I.mul_mem_right _ hCI
  have hsub := I.sub_mem hHI hmul
  have hdecomp := regularRemainder_add_mul_regularQuotient C H k
  rw [← hdecomp] at hsub
  simpa using hsub

/-- The remainder of an ideal element belongs to the bounded part of that
ideal. This is the ideal-membership content of equation (22). -/
theorem regularRemainder_mem_boundedPart
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C H : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C)
    (hCI : MvPolynomial.finSuccEquiv P n C ∈ I)
    (hHI : MvPolynomial.finSuccEquiv P n H ∈ I) :
    regularRemainder C k H ∈ boundedPart I k := by
  refine ⟨regularRemainder_mem_ideal I C H k hCI hHI, ?_⟩
  exact Polynomial.mem_degreeLT.mpr (degree_regularRemainder_lt C H hC)

/-- The `k` coefficients of the bounded representative in equation (22). -/
def regularCoefficientVector
    (C H : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    Fin k → MvPolynomial (Fin n) P :=
  Polynomial.degreeLTEquiv (MvPolynomial (Fin n) P) k
    ⟨regularRemainder C k H,
      Polynomial.mem_degreeLT.mpr (degree_regularRemainder_lt C H hC)⟩

/-- Equation (22)'s finite coefficient expansion of the regular remainder. -/
theorem regularRemainder_eq_sum_monomial
    (C H : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    regularRemainder C k H =
      ∑ i : Fin k, Polynomial.monomial (i : ℕ)
        (regularCoefficientVector C H hC i) := by
  let r : Polynomial.degreeLT (MvPolynomial (Fin n) P) k :=
    ⟨regularRemainder C k H,
      Polynomial.mem_degreeLT.mpr (degree_regularRemainder_lt C H hC)⟩
  have h := (Polynomial.degreeLTEquiv (MvPolynomial (Fin n) P) k).symm_apply_apply r
  have hval := congrArg Subtype.val h
  simpa [Polynomial.degreeLTEquiv, regularCoefficientVector, r] using hval.symm

/-- Full equation (22): the finite coefficient polynomial plus a multiple of
the original regular polynomial recovers `H`. -/
theorem finSuccEquiv_eq_sum_monomial_add_mul_regularQuotient
    (C H : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C) :
    MvPolynomial.finSuccEquiv P n H =
      (∑ i : Fin k, Polynomial.monomial (i : ℕ)
        (regularCoefficientVector C H hC i)) +
      MvPolynomial.finSuccEquiv P n C * regularQuotient C k H := by
  rw [← regularRemainder_eq_sum_monomial C H hC]
  exact (regularRemainder_add_mul_regularQuotient C H k).symm

/-- Equation (23): an ideal containing `C` is the sum of its bounded
remainder part and the principal tail generated by `C`. -/
theorem regularIdeal_eq_boundedPart_sup_principalTail
    (I : Ideal (Polynomial (MvPolynomial (Fin n) P)))
    (C : MvPolynomial (Fin (n + 1)) P)
    (hC : IsRegularInDegree (0 : Fin (n + 1)) k C)
    (hCI : MvPolynomial.finSuccEquiv P n C ∈ I) :
    I.restrictScalars (MvPolynomial (Fin n) P) =
      boundedPart I k ⊔ principalTail C := by
  apply le_antisymm
  · intro H hHI
    let Hmv : MvPolynomial (Fin (n + 1)) P :=
      (MvPolynomial.finSuccEquiv P n).symm H
    have hHmv : MvPolynomial.finSuccEquiv P n Hmv ∈ I := by
      simpa [Hmv] using hHI
    have hrem : regularRemainder C k Hmv ∈ boundedPart I k :=
      regularRemainder_mem_boundedPart I C Hmv hC hCI hHmv
    have hgen : MvPolynomial.finSuccEquiv P n C ∈
        Ideal.span ({MvPolynomial.finSuccEquiv P n C} :
          Set (Polynomial (MvPolynomial (Fin n) P))) :=
      Ideal.subset_span (by simp)
    have htail : MvPolynomial.finSuccEquiv P n C *
        regularQuotient C k Hmv ∈ principalTail C := by
      change MvPolynomial.finSuccEquiv P n C * regularQuotient C k Hmv ∈
        Ideal.span ({MvPolynomial.finSuccEquiv P n C} :
          Set (Polynomial (MvPolynomial (Fin n) P)))
      exact (Ideal.span ({MvPolynomial.finSuccEquiv P n C} :
        Set (Polynomial (MvPolynomial (Fin n) P)))).mul_mem_right _ hgen
    have hsum : regularRemainder C k Hmv +
        MvPolynomial.finSuccEquiv P n C * regularQuotient C k Hmv ∈
        boundedPart I k ⊔ principalTail C :=
      (boundedPart I k ⊔ principalTail C).add_mem
        ((show boundedPart I k ≤ boundedPart I k ⊔ principalTail C from
          le_sup_left) hrem)
        ((show principalTail C ≤ boundedPart I k ⊔ principalTail C from
          le_sup_right) htail)
    rw [regularRemainder_add_mul_regularQuotient C Hmv k] at hsum
    simpa [Hmv] using hsum
  · apply sup_le
    · intro H hH
      exact hH.1
    · intro H hH
      have hspan : Ideal.span ({MvPolynomial.finSuccEquiv P n C} :
          Set (Polynomial (MvPolynomial (Fin n) P))) ≤ I :=
        Ideal.span_le.mpr (by simpa using hCI)
      exact hspan hH

#print axioms boundedPart
#print axioms principalTail
#print axioms regularRemainder_mem_ideal
#print axioms regularRemainder_mem_boundedPart
#print axioms regularCoefficientVector
#print axioms regularRemainder_eq_sum_monomial
#print axioms finSuccEquiv_eq_sum_monomial_add_mul_regularQuotient
#print axioms regularIdeal_eq_boundedPart_sup_principalTail

end

end RegularIdealDecomposition

end MathematicalCommons.Noether.PolynomialIdealsAndResultants1923
