import MathematicalCommons.Noether.PolynomialIdealsAndResultants1923.CommonTailQuotient
import Mathlib.LinearAlgebra.Determinant
import Mathlib.LinearAlgebra.FreeModule.Finite.Quotient

/-!
# Hentzelt--Noether equation (24): Smith form after common-tail cancellation

Module for P22, controlled witness `NOETH-DE-ED-0014`, SHA-256
`EE226847656BC4D65EDDA9E9BF9BB1D25797C0C6D672D267D94A97FD88C7AD58`,
lines 13164--13173.  After adjoining the later variables to the coefficient
field, the source chooses bases
`G₁* = (η₁, ..., ηρ)` and `M₁* = (e₁η₁, ..., eρηρ)` and reads the `eᵢ` as
elementary divisors.  Mathlib supplies a Smith decomposition for a
full-rank submodule of a finite free module over a principal ideal domain.

This file gives source-facing names for the numerator basis, denominator
basis, Smith coefficients, and cyclic quotient decomposition, and composes
that decomposition with equation (23)'s common-tail equivalence.  It is
generic packaging, not yet an instantiation of Noether's historical
`G₁*` and `M₁*`: that still requires constructing those linear-form modules,
localizing the remaining-variable coefficient ring to a PID, and proving the
denominator has full rank.
-/

namespace MathematicalCommons.Noether.PolynomialIdealsAndResultants1923

namespace SmithPairedQuotient

noncomputable section

open Module

variable {ι R E : Type*}
variable [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
variable [AddCommGroup E] [Module R E] [Finite ι]

/-- The Smith basis of the relative numerator.  In equation (24), its vectors
are the `ηᵢ`. -/
noncomputable def relativeSmithTopBasis
    (G M : Submodule R E) (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) :
    Basis ι R G :=
  (CommonTailQuotient.relativeDenominator G M).smithNormalFormTopBasis b h

/-- The Smith basis of the relative denominator.  Its image in `G` consists
of the vectors `eᵢ • ηᵢ` from equation (24). -/
noncomputable def relativeSmithBottomBasis
    (G M : Submodule R E) (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) :
    Basis ι R (CommonTailQuotient.relativeDenominator G M) :=
  (CommonTailQuotient.relativeDenominator G M).smithNormalFormBotBasis b h

/-- The diagonal coefficients corresponding to the source's `eᵢ`. -/
noncomputable def relativeSmithCoefficients
    (G M : Submodule R E) (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) :
    ι → R :=
  (CommonTailQuotient.relativeDenominator G M).smithNormalFormCoeffs b h

/-- The denominator Smith basis maps to `eᵢ • ηᵢ` in the numerator. -/
@[simp]
theorem relativeSmithBottomBasis_eq_smul
    (G M : Submodule R E) (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) (i : ι) :
    ((relativeSmithBottomBasis G M b h i :
        CommonTailQuotient.relativeDenominator G M) : G) =
      relativeSmithCoefficients G M b h i •
        relativeSmithTopBasis G M b h i := by
  exact Submodule.smithNormalFormBotBasis_def b h i

/-- Each chosen Smith coefficient is nonzero under the full-rank hypothesis. -/
theorem relativeSmithCoefficients_ne_zero
    (G M : Submodule R E) (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) (i : ι) :
    relativeSmithCoefficients G M b h i ≠ 0 := by
  exact Submodule.smithNormalFormCoeffs_ne_zero b h i

/-- Every denominator Smith-basis vector, viewed in the original ambient
module, belongs to the ambient denominator `M`. -/
theorem relativeSmithBottomBasis_mem
    (G M : Submodule R E) (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) (i : ι) :
    ((((relativeSmithBottomBasis G M b h i :
        CommonTailQuotient.relativeDenominator G M) : G) : E)) ∈ M := by
  exact (relativeSmithBottomBasis G M b h i).property

/-- The relative quotient `G / M` is the product of the cyclic quotients by
the principal ideals generated by the Smith coefficients. -/
noncomputable def relativeQuotientEquivSmithCyclic
    (G M : Submodule R E) (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) :
    CommonTailQuotient.relativeQuotient G M ≃ₗ[R]
      (∀ i, R ⧸ Ideal.span
        ({relativeSmithCoefficients G M b h i} : Set R)) :=
  (CommonTailQuotient.relativeDenominator G M).quotientEquivPiSpan b h

/-- Equation (23)'s common tail may first be cancelled and the remaining
relative quotient then decomposed into its Smith cyclic factors. -/
noncomputable def commonTailQuotientEquivSmithCyclic
    (G M T : Submodule R E) (hMG : M ≤ G) (hGT : Disjoint G T)
    (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) :
    CommonTailQuotient.relativeQuotient (G ⊔ T) (M ⊔ T) ≃ₗ[R]
      (∀ i, R ⧸ Ideal.span
        ({relativeSmithCoefficients G M b h i} : Set R)) :=
  (CommonTailQuotient.commonTailQuotientEquiv G M T hMG hGT).trans
    (relativeQuotientEquivSmithCyclic G M b h)

/-- In the selected Smith bases, the determinant of the inclusion of the
denominator into the numerator is exactly the product of the chosen diagonal
coefficients.  This is the chosen-basis equality underlying the product formulas
used after equation (24); arbitrary independent basis choices give equality
only up to association. -/
theorem det_relativeSmithBasisTransition_eq_prod [Fintype ι]
    (G M : Submodule R E) (b : Basis ι R G)
    (h : Module.finrank R (CommonTailQuotient.relativeDenominator G M) =
      Module.finrank R G) :
    LinearMap.det
        ((CommonTailQuotient.relativeDenominator G M).subtype.comp
          (((relativeSmithTopBasis G M b h).equiv
            (relativeSmithBottomBasis G M b h) (Equiv.refl ι)).toLinearMap)) =
      ∏ i, relativeSmithCoefficients G M b h i := by
  classical
  let bG := relativeSmithTopBasis G M b h
  let bM := relativeSmithBottomBasis G M b h
  let a := relativeSmithCoefficients G M b h
  let e := bG.equiv bM (Equiv.refl ι)
  let f : G →ₗ[R] G :=
    (CommonTailQuotient.relativeDenominator G M).subtype.comp
      e.toLinearMap
  have hf : ∀ i, f (bG i) = a i • bG i := by
    intro i
    rw [show f (bG i) = (bM i : G) by simp [f, e, bG, bM]]
    exact relativeSmithBottomBasis_eq_smul G M b h i
  change LinearMap.det f = ∏ i, a i
  rw [← LinearMap.det_toMatrix bG]
  have hmatrix : LinearMap.toMatrix bG bG f = Matrix.diagonal a := by
    ext i j
    rw [LinearMap.toMatrix_apply, hf, map_smul, Basis.repr_self,
      Finsupp.smul_single, smul_eq_mul, mul_one]
    by_cases hij : i = j
    · rw [hij, Matrix.diagonal_apply_eq, Finsupp.single_eq_same]
    · rw [Matrix.diagonal_apply_ne _ hij, Finsupp.single_eq_of_ne hij]
  rw [hmatrix, Matrix.det_diagonal]

#print axioms relativeSmithTopBasis
#print axioms relativeSmithBottomBasis
#print axioms relativeSmithCoefficients
#print axioms relativeSmithBottomBasis_eq_smul
#print axioms relativeSmithCoefficients_ne_zero
#print axioms relativeSmithBottomBasis_mem
#print axioms relativeQuotientEquivSmithCyclic
#print axioms commonTailQuotientEquivSmithCyclic
#print axioms det_relativeSmithBasisTransition_eq_prod

end

end SmithPairedQuotient

end MathematicalCommons.Noether.PolynomialIdealsAndResultants1923
