/-
Copyright (c) 2026 Lean of the Mathematical Commons contributors.
SPDX-License-Identifier: Apache-2.0
-/
import Mathlib.RingTheory.Invariant.Basic
import Mathlib.RingTheory.Adjoin.Tower

/-!
# Emmy Noether, finite-group invariants in characteristic p (1926)

Source: Emmy Noether, *Der Endlichkeitssatz der Invarianten endlicher linearer
Gruppen der Charakteristik p*, controlled witness `NOETH-DE-ED-0014`, SHA-256
`EE226847656BC4D65EDDA9E9BF9BB1D25797C0C6D672D267D94A97FD88C7AD58`,
lines 14243–14341.

Noether's main result at line 14257 is finite generation as an algebra of the
invariants of a finite linear group over an arbitrary field, including when
the characteristic divides the group order. Lines 14319–14335 derive
integrality from the orbit resolvent and then finite generation.

Mathlib already supplies the orbit-polynomial integrality theorem
`Algebra.IsInvariant.isIntegral`, but fixed-ring integrality is not itself the
finite-generation conclusion. This module adds the Artin–Tate descent step. It
works for any finite group action on a finite-type commutative algebra over a
Noetherian base and therefore does not need characteristic, linearity, or
faithfulness assumptions.

The module does not formalize Noether's explicit universal-resolvent generator
family, rational-basis criterion, relative-invariant predicate, or pointwise
modular-invariant predicate. The intermediate-subalgebra theorem applies to
the latter rings only after they are modeled and shown to contain the fixed
subalgebra.
-/

namespace MathematicalCommons.Noether.ModularInvariants1926

variable (A B G : Type*) [CommRing A] [CommRing B] [Algebra A B]
  [Group G] [Finite G] [MulSemiringAction G B] [SMulCommClass G A B]

/-- Every intermediate subalgebra containing the fixed points is finite type
over the base, provided the ambient algebra is finite type and the base is
Noetherian.

This combines finite-group integrality with Artin–Tate. It also supplies the
abstract final step for rings generated by relative or pointwise invariants,
once their source-specific containment statements are formalized. -/
theorem subalgebra_finiteType_of_fixedPoints_le
    [IsNoetherianRing A] [Algebra.FiniteType A B]
    (C : Subalgebra A B) (hC : FixedPoints.subalgebra A B G ≤ C) :
    Algebra.FiniteType A C := by
  letI : Algebra.IsInvariant C B G :=
    ⟨fun b hb ↦ ⟨⟨b, hC hb⟩, rfl⟩⟩
  letI : Algebra.IsIntegral C B := Algebra.IsInvariant.isIntegral C B G
  letI : Algebra.FiniteType C B :=
    Algebra.FiniteType.of_restrictScalars_finiteType A C B
  letI : Module.Finite C B := Algebra.IsIntegral.finite
  exact ⟨fg_of_fg_of_fg A C B
    (‹Algebra.FiniteType A B›.out)
    Module.Finite.fg_top (FaithfulSMul.algebraMap_injective C B)⟩

/-- If a finite group acts on a finite-type algebra over a Noetherian ring and
fixes the base ring, then its fixed subalgebra is finite type over the base.

This is the characteristic-free modern form of Noether's main 1926
finite-generation theorem. -/
theorem fixedPoints_finiteType
    [IsNoetherianRing A] [Algebra.FiniteType A B] :
    Algebra.FiniteType A (FixedPoints.subalgebra A B G) :=
  subalgebra_finiteType_of_fixedPoints_le A B G _ le_rfl

#print axioms subalgebra_finiteType_of_fixedPoints_le
#print axioms fixedPoints_finiteType

end MathematicalCommons.Noether.ModularInvariants1926

