/-
Copyright (c) 2026 Lean of the Mathematical Commons contributors.
SPDX-License-Identifier: Apache-2.0
-/
import Mathlib.Algebra.Algebra.Operations
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.Module.Submodule.RestrictScalars
import Mathlib.Algebra.MvPolynomial.Degrees
import Mathlib.Algebra.Polynomial.EraseLead
import Mathlib.Algebra.Polynomial.Coeff
import Mathlib.Data.Nat.Digits.Defs
import Mathlib.RingTheory.Ideal.Colon
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.Polynomial.ContentIdeal
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.Tactic.Ring

/-!
# Hentzelt--Noether 1923: Dedekind--Mertens and Satz VIII

Controlled source: Kurt Hentzelt, freely edited and conceptually recast by
Emmy Noether, *Zur Theorie der Polynomideale und Resultanten*, witness
`NOETH-DE-ED-0014`, SHA-256
`EE226847656BC4D65EDDA9E9BF9BB1D25797C0C6D672D267D94A97FD88C7AD58`.

Satz VI cites the Dedekind--Mertens identity at lines 13059--13077 in
existential-exponent form for coefficient modules of multivariate
polynomials. This file proves unrestricted univariate Dedekind--Mertens for
coefficient submodules over an arbitrary commutative base ring and then uses a
bounded Kronecker encoding to prove the literal multivariate identity (17).
The `A = ℤ` specialization has the source's integer-linear semantics, while
`A = R` recovers Mathlib's content ideal. It also packages the coefficientwise
ideal-membership inference used between equations (19) and (20), retains the
direct degree-one proof, and supplies an explicit `q = 2` instance. The
historical generic-coordinate, localization, and successive-ground-ideal
identifications remain separate work.

Satz VIII proves that the elementary-divisor form divides the resultant form
and that the resultant form divides a power of the elementary-divisor form.
The lemmas below package the immediate consequence used in elimination:
the two forms have the same radical and the same zeros over a field. They do
not construct the stage resultants or prove Hentzelt's divisibility assertions.
-/

namespace MathematicalCommons.Noether.PolynomialIdealsAndResultants1923

open Ideal Polynomial

section RelativeCoefficientModules

variable {A R : Type*} [CommRing A] [CommRing R] [Algebra A R]

/-- The module over the base ring generated by the coefficients of a
univariate polynomial.  For `A = R`, this has the same carrier as the usual
content ideal, but the definition also records Hentzelt--Noether's genuinely
relative coefficient-module setting. -/
def coefficientModule (p : R[X]) : Submodule A R :=
  Submodule.span A (p.coeffs : Set R)

/-- Over the coefficient ring itself, the relative coefficient module is
definitionally Mathlib's content ideal.  This is the bridge used to retain the
existing ideal-facing API as thin specializations of the generic theorem. -/
@[simp]
theorem coefficientModule_self_eq_contentIdeal (p : R[X]) :
    coefficientModule (A := R) p = p.contentIdeal :=
  rfl

/-- Every coefficient belongs to the coefficient module. -/
theorem coeff_mem_coefficientModule (p : R[X]) (n : ℕ) :
    p.coeff n ∈ coefficientModule (A := A) p := by
  by_cases h : p.coeff n = 0
  · simp [h]
  · apply Submodule.subset_span
    simpa using p.coeff_mem_coeffs h

/-- The coefficient module of a monomial is generated by its coefficient. -/
@[simp]
theorem coefficientModule_monomial (n : ℕ) (r : R) :
    coefficientModule (A := A) (monomial n r) = Submodule.span A {r} := by
  by_cases h : r = 0 <;>
    simp [h, coefficientModule, Polynomial.coeffs_monomial]

/-- The coefficient module of a constant polynomial. -/
@[simp]
theorem coefficientModule_C (r : R) :
    coefficientModule (A := A) (C r) = Submodule.span A {r} := by
  rw [← monomial_zero_left]
  exact coefficientModule_monomial 0 r

/-- The formal easy containment for coefficient modules of a product. -/
theorem coefficientModule_mul_le_mul_coefficientModule (f g : R[X]) :
    coefficientModule (A := A) (f * g) ≤
      coefficientModule (A := A) f * coefficientModule (A := A) g := by
  rw [coefficientModule, Submodule.span_le]
  simp only [Set.subset_def, Finset.mem_coe, Polynomial.mem_coeffs_iff]
  rintro r ⟨n, -, rfl⟩
  simp [Polynomial.coeff_mul, Submodule.sum_mem, Submodule.mul_mem_mul,
    coeff_mem_coefficientModule]

/-- Multiplication by a constant polynomial multiplies the coefficient module
by the corresponding cyclic submodule. -/
theorem coefficientModule_mul_C_eq (f : R[X]) (b : R) :
    coefficientModule (A := A) (f * C b) =
      coefficientModule (A := A) f * Submodule.span A {b} := by
  apply le_antisymm
  · simpa using coefficientModule_mul_le_mul_coefficientModule (A := A) f (C b)
  · change
      Submodule.span A (f.coeffs : Set R) * Submodule.span A ({b} : Set R) ≤
        coefficientModule (A := A) (f * C b)
    rw [Submodule.span_mul_span, Submodule.span_le]
    rintro x ⟨a, ha, c, hc, rfl⟩
    simp only [Set.mem_singleton_iff] at hc
    subst c
    simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at ha
    obtain ⟨i, -, rfl⟩ := ha
    simpa [Polynomial.coeff_mul_C] using
      coeff_mem_coefficientModule (A := A) (f * C b) i

/-- Removing one coefficient loses at most the cyclic module generated by
that coefficient. -/
theorem coefficientModule_le_erase_sup_span (g : R[X]) (m : ℕ) :
    coefficientModule (A := A) g ≤
      coefficientModule (A := A) (g.erase m) ⊔
        Submodule.span A {g.coeff m} := by
  rw [coefficientModule, Submodule.span_le]
  intro x hx
  simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at hx
  obtain ⟨i, -, rfl⟩ := hx
  by_cases hi : i = m
  · subst i
    exact (show Submodule.span A {g.coeff m} ≤
      coefficientModule (A := A) (g.erase m) ⊔
        Submodule.span A {g.coeff m} from le_sup_right)
      (Submodule.subset_span (by simp))
  · apply (show coefficientModule (A := A) (g.erase m) ≤
      coefficientModule (A := A) (g.erase m) ⊔
        Submodule.span A {g.coeff m} from le_sup_left)
    have hmem := coeff_mem_coefficientModule (A := A) (g.erase m) i
    simpa [Polynomial.coeff_erase, hi] using hmem

/-- The product with one coefficient erased is controlled by the original
product module and the erased coefficient times the first coefficient
module. -/
theorem coefficientModule_mul_erase_le (f g : R[X]) (m : ℕ) :
    coefficientModule (A := A) (f * g.erase m) ≤
      coefficientModule (A := A) (f * g) ⊔
        coefficientModule (A := A) f * Submodule.span A {g.coeff m} := by
  let t : R[X] := monomial m (g.coeff m)
  have hpoly : f * g.erase m + f * t = f * g := by
    rw [← mul_add]
    congr 1
    simpa [t, add_comm] using g.monomial_add_erase m
  rw [coefficientModule, Submodule.span_le]
  intro x hx
  simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at hx
  obtain ⟨k, -, rfl⟩ := hx
  have hcoeff := congrArg (fun p : R[X] ↦ p.coeff k) hpoly
  simp only [Polynomial.coeff_add] at hcoeff
  have hleft : (f * g).coeff k ∈
      coefficientModule (A := A) (f * g) ⊔
        coefficientModule (A := A) f * Submodule.span A {g.coeff m} :=
    (show coefficientModule (A := A) (f * g) ≤
      coefficientModule (A := A) (f * g) ⊔
        coefficientModule (A := A) f * Submodule.span A {g.coeff m} from
          le_sup_left)
      (coeff_mem_coefficientModule (A := A) (f * g) k)
  have hterm0 :=
    coefficientModule_mul_le_mul_coefficientModule (A := A) f t
      (coeff_mem_coefficientModule (A := A) (f * t) k)
  have hterm : (f * t).coeff k ∈
      coefficientModule (A := A) (f * g) ⊔
        coefficientModule (A := A) f * Submodule.span A {g.coeff m} := by
    apply (show coefficientModule (A := A) f * Submodule.span A {g.coeff m} ≤
      coefficientModule (A := A) (f * g) ⊔
        coefficientModule (A := A) f * Submodule.span A {g.coeff m} from
          le_sup_right)
    simpa [t] using hterm0
  rw [eq_sub_of_add_eq hcoeff]
  exact (coefficientModule (A := A) (f * g) ⊔
    coefficientModule (A := A) f * Submodule.span A {g.coeff m}).sub_mem
      hleft hterm

/-- Multiplication by a cyclic submodule can be checked on its displayed
generator. -/
theorem span_singleton_mul_le_iff {x : R} {M N : Submodule A R} :
    Submodule.span A {x} * M ≤ N ↔ ∀ y ∈ M, x * y ∈ N := by
  constructor
  · intro h y hy
    exact h (Submodule.mul_mem_mul (Submodule.subset_span (by simp)) hy)
  · intro h y hy
    obtain ⟨z, hz, hxz⟩ := Submodule.mem_span_singleton_mul.mp hy
    rw [← hxz]
    exact h z hz

/-- A multiplication containment from a coefficient module follows once it
has been checked on every coefficient. -/
theorem coefficientModule_mul_le_of_coefficients
    (f : R[X]) (M K : Submodule A R)
    (h : ∀ i : ℕ, Submodule.span A {f.coeff i} * M ≤ K) :
    coefficientModule (A := A) f * M ≤ K := by
  rw [Submodule.mul_le]
  intro a ha z hz
  change a ∈ Submodule.span A (f.coeffs : Set R) at ha
  induction ha using Submodule.span_induction with
  | mem a ha =>
      simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at ha
      obtain ⟨i, -, rfl⟩ := ha
      exact (span_singleton_mul_le_iff.mp (h i)) z hz
  | zero => simp
  | add x y _ _ hx hy =>
      rw [add_mul]
      exact K.add_mem hx hy
  | smul c x _ hx =>
      rw [Algebra.smul_mul_assoc]
      exact K.smul_mem c hx

/-- The difficult containment in the relative coefficient-module
Dedekind--Mertens lemma, stated for an arbitrary formal degree bound on the
second polynomial. -/
theorem dedekindMertens_coefficientModule_hard_bound
    (f g : R[X]) (m : ℕ) (hg : g.natDegree ≤ m) :
    coefficientModule (A := A) f ^ (m + 1) *
        coefficientModule (A := A) g ≤
      coefficientModule (A := A) f ^ m *
        coefficientModule (A := A) (f * g) := by
  induction m generalizing g with
  | zero =>
      have hg0 : g.natDegree = 0 := Nat.eq_zero_of_le_zero hg
      rw [Polynomial.eq_C_of_natDegree_eq_zero hg0]
      simp [coefficientModule_mul_C_eq]
  | succ n ih =>
      let m := n + 1
      let F : Submodule A R := coefficientModule (A := A) f
      let Q : Submodule A R := coefficientModule (A := A) (g.erase m)
      let b : R := g.coeff m
      let H : Submodule A R := coefficientModule (A := A) (f * g)
      let K : Submodule A R := F ^ m * H
      have hm : m = n + 1 := rfl
      have hqdeg : (g.erase m).natDegree ≤ n := by
        rw [Polynomial.natDegree_le_iff_coeff_eq_zero]
        intro j hj
        rw [Polynomial.coeff_erase]
        split_ifs with heq
        · rfl
        · apply g.coeff_eq_zero_of_natDegree_lt
          have hmj : m < j := by
            have hmle : m ≤ j := by
              simpa [m] using (Nat.succ_le_iff.mpr hj)
            exact lt_of_le_of_ne hmle (fun h ↦ heq h.symm)
          exact hg.trans_lt (by simpa [m] using hmj)
      have hrec : F ^ m * Q ≤
          F ^ n * coefficientModule (A := A) (f * g.erase m) := by
        simpa [F, Q, m] using ih (g.erase m) hqdeg
      have herase : coefficientModule (A := A) (f * g.erase m) ≤
          H ⊔ F * Submodule.span A {b} := by
        simpa [F, H, b] using coefficientModule_mul_erase_le (A := A) f g m

      let P : ℕ → Prop := fun i ↦
        Submodule.span A {f.coeff i} * (F ^ m * Q) ≤ K
      let B : ℕ → Prop := fun i ↦
        Submodule.span A {f.coeff i * b} * F ^ m ≤ K
      let Tail : ℕ → Prop := fun i ↦
        ∀ j, i ≤ j → P j ∧ B j

      have htail_top : Tail (f.natDegree + 1) := by
        intro j hj
        have hzero : f.coeff j = 0 :=
          f.coeff_eq_zero_of_natDegree_lt
            ((Nat.lt_succ_self f.natDegree).trans_le hj)
        simp [P, B, hzero]

      have htail_step : ∀ i < f.natDegree + 1,
          Tail (i + 1) → Tail i := by
        intro i hi htail j hij
        by_cases hji : j = i
        · subst j
          have hB : B i := by
            change Submodule.span A {f.coeff i * b} * F ^ m ≤ K
            rw [span_singleton_mul_le_iff]
            intro u hu
            let S := (Finset.antidiagonal (i + m)).erase (i, m)
            have himem : (i, m) ∈ Finset.antidiagonal (i + m) := by
              simp
            have hconv : (f * g).coeff (i + m) =
                f.coeff i * b +
                  ∑ p ∈ S, f.coeff p.1 * g.coeff p.2 := by
              rw [Polynomial.coeff_mul,
                ← Finset.insert_erase himem,
                Finset.sum_insert (Finset.notMem_erase _ _)]
            have hmain : (f * g).coeff (i + m) * u ∈ K := by
              simpa [mul_comm] using Submodule.mul_mem_mul hu
                (coeff_mem_coefficientModule (A := A) (f * g) (i + m))
            have hsum :
                (∑ p ∈ S, f.coeff p.1 * g.coeff p.2) * u ∈ K := by
              rw [Finset.sum_mul]
              apply K.sum_mem
              intro p hp
              rw [Finset.mem_erase, Finset.mem_antidiagonal] at hp
              rcases p with ⟨x, y⟩
              by_cases hym : m < y
              · have hgy : g.coeff y = 0 :=
                  g.coeff_eq_zero_of_natDegree_lt
                    (hg.trans_lt (by simpa [m] using hym))
                simp [hgy]
              · have hymle : y ≤ m := Nat.le_of_not_gt hym
                have hyne : y ≠ m := by
                  intro hy
                  apply hp.1
                  have hx : x = i := by
                    simpa [hy] using hp.2
                  simp [hx, hy]
                have hylt : y < m := lt_of_le_of_ne hymle hyne
                have hix : i < x := by
                  by_contra hix
                  have hbad : x + y < i + m :=
                    Nat.add_lt_add_of_le_of_lt (Nat.le_of_not_gt hix) hylt
                  rw [hp.2] at hbad
                  exact (Nat.lt_irrefl _ hbad)
                have hqcoeff : g.coeff y ∈ Q := by
                  have hmem :=
                    coeff_mem_coefficientModule (A := A) (g.erase m) y
                  simpa [Q, Polynomial.coeff_erase, hyne] using hmem
                have hPx := (htail x (Nat.succ_le_iff.mpr hix)).1
                have hPx' := span_singleton_mul_le_iff.mp hPx
                have huz : u * g.coeff y ∈ F ^ m * Q :=
                  Submodule.mul_mem_mul hu hqcoeff
                convert hPx' (u * g.coeff y) huz using 1
                all_goals ring
            rw [hconv] at hmain
            convert K.sub_mem hmain hsum using 1
            all_goals ring
          have hP : P i := by
            change Submodule.span A {f.coeff i} * (F ^ m * Q) ≤ K
            rw [span_singleton_mul_le_iff]
            intro z hz
            have hz' : z ∈
                F ^ n * coefficientModule (A := A) (f * g.erase m) := hrec hz
            have hmul : Submodule.span A {f.coeff i} *
                (F ^ n * coefficientModule (A := A) (f * g.erase m)) ≤ K := by
              calc
                Submodule.span A {f.coeff i} *
                    (F ^ n * coefficientModule (A := A) (f * g.erase m))
                    ≤ Submodule.span A {f.coeff i} *
                        (F ^ n * (H ⊔ F * Submodule.span A {b})) :=
                  mul_le_mul' le_rfl (mul_le_mul' le_rfl herase)
                _ = (Submodule.span A {f.coeff i} * (F ^ n * H)) ⊔
                    (Submodule.span A {f.coeff i} *
                      (F ^ n * (F * Submodule.span A {b}))) := by
                  rw [Submodule.mul_sup, Submodule.mul_sup]
                _ ≤ K := by
                  apply sup_le
                  · calc
                      Submodule.span A {f.coeff i} * (F ^ n * H)
                          = (Submodule.span A {f.coeff i} * F ^ n) * H := by
                            rw [mul_assoc]
                      _ ≤ (F * F ^ n) * H :=
                        mul_le_mul'
                          (mul_le_mul'
                            (Submodule.span_le.mpr
                              (Set.singleton_subset_iff.mpr
                                (coeff_mem_coefficientModule (A := A) f i)))
                            le_rfl)
                          le_rfl
                      _ = K := by
                        simp only [K, hm]
                        rw [pow_succ]
                        ac_rfl
                  · have hrew :
                        Submodule.span A {f.coeff i} *
                            (F ^ n * (F * Submodule.span A {b})) =
                          Submodule.span A {f.coeff i * b} * F ^ m := by
                        have hspan :
                            Submodule.span A {f.coeff i} *
                                Submodule.span A {b} =
                              Submodule.span A {f.coeff i * b} := by
                          rw [Submodule.span_mul_span]
                          simp
                        simp only [hm]
                        rw [pow_succ]
                        calc
                          Submodule.span A {f.coeff i} *
                                (F ^ n * (F * Submodule.span A {b})) =
                              (Submodule.span A {f.coeff i} *
                                Submodule.span A {b}) * (F ^ n * F) := by
                            ac_rfl
                          _ = Submodule.span A {f.coeff i * b} *
                                (F ^ n * F) := by rw [hspan]
                    rw [hrew]
                    exact hB
            exact (span_singleton_mul_le_iff.mp hmul) z hz'
          exact ⟨hP, hB⟩
        · have hijlt : i < j := lt_of_le_of_ne hij (Ne.symm hji)
          exact htail j (Nat.succ_le_iff.mpr hijlt)

      have htail_zero : Tail 0 :=
        Nat.decreasingInduction
          (n := f.natDegree + 1)
          (fun i hi htail ↦ htail_step i hi htail)
          htail_top (Nat.zero_le _)
      have hall (i : ℕ) : P i ∧ B i := htail_zero i (Nat.zero_le i)

      have hQ : F * (F ^ m * Q) ≤ K := by
        change coefficientModule (A := A) f * (F ^ m * Q) ≤ K
        exact coefficientModule_mul_le_of_coefficients f (F ^ m * Q) K
          (fun i ↦ (hall i).1)

      have hb' : F * (Submodule.span A {b} * F ^ m) ≤ K := by
        change coefficientModule (A := A) f *
          (Submodule.span A {b} * F ^ m) ≤ K
        apply coefficientModule_mul_le_of_coefficients f
          (Submodule.span A {b} * F ^ m) K
        intro i
        rw [span_singleton_mul_le_iff]
        intro z hz
        obtain ⟨u, hu, rfl⟩ := Submodule.mem_span_singleton_mul.mp hz
        have hi := span_singleton_mul_le_iff.mp (hall i).2 u hu
        convert hi using 1
        all_goals ring
      have hb : (F * Submodule.span A {b}) * F ^ m ≤ K := by
        rw [mul_assoc]
        exact hb'

      have hG : coefficientModule (A := A) g ≤
          Q ⊔ Submodule.span A {b} := by
        simpa [Q, b] using coefficientModule_le_erase_sup_span (A := A) g m
      calc
        coefficientModule (A := A) f ^ (n + 1 + 1) *
              coefficientModule (A := A) g
            ≤ F ^ (m + 1) * (Q ⊔ Submodule.span A {b}) := by
              simpa [F, m] using mul_le_mul' le_rfl hG
        _ = (F ^ (m + 1) * Q) ⊔
              (F ^ (m + 1) * Submodule.span A {b}) := by
              rw [Submodule.mul_sup]
        _ ≤ K := by
          apply sup_le
          · have hrew : F ^ (m + 1) * Q = F * (F ^ m * Q) := by
              rw [pow_succ]
              ac_rfl
            rw [hrew]
            exact hQ
          · have hrew : F ^ (m + 1) * Submodule.span A {b} =
                (F * Submodule.span A {b}) * F ^ m := by
              rw [pow_succ]
              ac_rfl
            rw [hrew]
            exact hb
        _ = coefficientModule (A := A) f ^ (n + 1) *
              coefficientModule (A := A) (f * g) := by
          simp [K, F, H, m]

/-- Unrestricted univariate Dedekind--Mertens for coefficient modules over an
arbitrary commutative base ring. -/
theorem dedekindMertens_coefficientModule (f g : R[X]) :
    coefficientModule (A := A) f ^ (g.natDegree + 1) *
        coefficientModule (A := A) g =
      coefficientModule (A := A) f ^ g.natDegree *
        coefficientModule (A := A) (f * g) := by
  apply le_antisymm
  · exact dedekindMertens_coefficientModule_hard_bound f g g.natDegree le_rfl
  · calc
      coefficientModule (A := A) f ^ g.natDegree *
            coefficientModule (A := A) (f * g)
          ≤ coefficientModule (A := A) f ^ g.natDegree *
              (coefficientModule (A := A) f *
                coefficientModule (A := A) g) :=
        mul_le_mul' le_rfl
          (coefficientModule_mul_le_mul_coefficientModule (A := A) f g)
      _ = coefficientModule (A := A) f ^ (g.natDegree + 1) *
            coefficientModule (A := A) g := by
        rw [pow_succ]
        ac_rfl

end RelativeCoefficientModules

section SatzVIApplicationCore

variable {S : Type*} [CommRing S]

/-- If the product-coefficient module lies in an ideal, the
Dedekind--Mertens identity puts the entire left-hand coefficient module in
that ideal after restriction of scalars to `ℤ`. -/
theorem dedekindMertens_module_le_restrictScalars
    (I : Ideal S) {A B D : Submodule ℤ S} {q : ℕ}
    (hDM : A ^ q * B = A ^ (q - 1) * D)
    (hD : D ≤ I.restrictScalars ℤ) :
    A ^ q * B ≤ I.restrictScalars ℤ := by
  rw [hDM]
  refine Submodule.mul_le.mpr ?_
  intro a _ha d hd
  exact (Submodule.restrictScalars_mem ℤ I (a * d)).2
    (I.mul_mem_left a
      ((Submodule.restrictScalars_mem ℤ I d).1 (hD hd)))

/-- If every coefficient of a multivariate polynomial belongs to `A`, then
every coefficient of its `q`-th power belongs to `A ^ q`. -/
theorem mvPolynomial_coeff_pow_mem_submodule_pow
    {U : Type*} (A : Submodule ℤ S) (p : MvPolynomial U S)
    (hp : ∀ d : U →₀ ℕ, p.coeff d ∈ A) (q : ℕ) (d : U →₀ ℕ) :
    (p ^ q).coeff d ∈ A ^ q := by
  classical
  induction q generalizing d with
  | zero =>
      change MvPolynomial.coeff d (1 : MvPolynomial U S) ∈
        (1 : Submodule ℤ S)
      rw [MvPolynomial.coeff_one]
      split_ifs
      · exact Submodule.one_le.mp le_rfl
      · exact Submodule.zero_mem _
  | succ q ih =>
      change MvPolynomial.coeff d (p ^ q * p) ∈ A ^ q * A
      rw [MvPolynomial.coeff_mul]
      exact Submodule.sum_mem _ fun x _ =>
        Submodule.mul_mem_mul (ih x.1) (hp x.2)

/-- Polynomial form of the coefficient-module application: if `p` has
coefficients in `A` and `gamma` lies in `B`, then `p ^ q * C gamma` belongs
to the coefficient extension of `I`. -/
theorem mvPolynomial_pow_mul_C_mem_coefficientExtension
    {U : Type*} (I : Ideal S) {A B D : Submodule ℤ S} {q : ℕ}
    (hDM : A ^ q * B = A ^ (q - 1) * D)
    (hD : D ≤ I.restrictScalars ℤ)
    (p : MvPolynomial U S)
    (hp : ∀ d : U →₀ ℕ, p.coeff d ∈ A)
    {gamma : S} (hgamma : gamma ∈ B) :
    p ^ q * MvPolynomial.C gamma ∈
      Ideal.map (MvPolynomial.C : S →+* MvPolynomial U S) I := by
  rw [MvPolynomial.mem_map_C_iff]
  intro d
  have hmodule :=
    dedekindMertens_module_le_restrictScalars I hDM hD
  have hpow :=
    mvPolynomial_coeff_pow_mem_submodule_pow A p hp q d
  have hcoeff :
      (p ^ q * MvPolynomial.C gamma).coeff d ∈ A ^ q * B := by
    rw [mul_comm (p ^ q) (MvPolynomial.C gamma),
      MvPolynomial.coeff_C_mul,
      mul_comm gamma ((p ^ q).coeff d)]
    exact Submodule.mul_mem_mul hpow hgamma
  exact (Submodule.restrictScalars_mem ℤ I _).1 (hmodule hcoeff)

end SatzVIApplicationCore

namespace Kronecker

open scoped BigOperators
open Polynomial

variable {R : Type*} [CommSemiring R]
variable {n d base : ℕ}

/-- The base-power weighted sum of a multivariate exponent vector.  Bundling
it as an additive hom makes the compatibility with multiplication of
monomials explicit. -/
def weightedExponent (base : ℕ) : (Fin n →₀ ℕ) →+ ℕ where
  toFun e := ∑ i : Fin n, base ^ (i : ℕ) * e i
  map_zero' := by simp
  map_add' e f := by
    simp only [Finsupp.add_apply, mul_add, Finset.sum_add_distrib]

@[simp]
theorem weightedExponent_apply (base : ℕ) (e : Fin n →₀ ℕ) :
    weightedExponent base e = ∑ i : Fin n, base ^ (i : ℕ) * e i :=
  rfl

@[simp]
theorem weightedExponent_single (base : ℕ) (i : Fin n) (a : ℕ) :
    weightedExponent base (Finsupp.single i a) = base ^ (i : ℕ) * a := by
  classical
  rw [weightedExponent_apply, Finset.sum_eq_single i]
  · simp
  · intro j _ hji
    simp [hji]
  · simp

/-- `Nat.ofDigits` of a fixed-length coordinate list is its base-power
weighted sum.  This direct induction avoids the optional deprecated
`Mathlib.Data.List.Indexes` module. -/
private theorem ofDigits_ofFn_eq_sum (base : ℕ) :
    ∀ {m : ℕ} (e : Fin m → ℕ),
      Nat.ofDigits base (List.ofFn e) =
        ∑ i : Fin m, base ^ (i : ℕ) * e i := by
  intro m
  induction m with
  | zero =>
      intro e
      simp
  | succ m ih =>
      intro e
      rw [List.ofFn_succ, Nat.ofDigits_cons, Fin.sum_univ_succ, ih]
      simp only [Fin.val_zero, pow_zero, one_mul, Fin.val_succ]
      rw [Finset.mul_sum]
      congr 1
      apply Finset.sum_congr rfl
      intro i _
      simp [pow_succ, mul_comm, mul_left_comm]

/-- The weighted exponent is exactly the natural number represented by the
coordinate list in base `base`. -/
theorem ofDigits_ofFn_eq_weightedExponent (base : ℕ) (e : Fin n →₀ ℕ) :
    Nat.ofDigits base (List.ofFn fun i : Fin n => e i) =
      weightedExponent base e := by
  simpa only [weightedExponent_apply] using
    ofDigits_ofFn_eq_sum base (fun i : Fin n => e i)

/-- Base-power weighted sums separate exponent vectors whose coordinates are
valid base-`base` digits. -/
theorem weightedExponent_injective_of_lt_base
    (hbase : 1 < base) {e f : Fin n →₀ ℕ}
    (he : ∀ i, e i < base) (hf : ∀ i, f i < base)
    (hcode : weightedExponent base e = weightedExponent base f) :
    e = f := by
  have hdigits :
      Nat.ofDigits base (List.ofFn fun i : Fin n => e i) =
        Nat.ofDigits base (List.ofFn fun i : Fin n => f i) := by
    calc
      Nat.ofDigits base (List.ofFn fun i : Fin n => e i) =
          weightedExponent base e :=
        ofDigits_ofFn_eq_weightedExponent base e
      _ = weightedExponent base f := hcode
      _ = Nat.ofDigits base (List.ofFn fun i : Fin n => f i) :=
        (ofDigits_ofFn_eq_weightedExponent base f).symm
  have hlists :
      List.ofFn (fun i : Fin n => e i) =
        List.ofFn (fun i : Fin n => f i) :=
    Nat.ofDigits_inj_of_len_eq hbase (by simp)
      ((List.forall_mem_ofFn_iff).2 he)
      ((List.forall_mem_ofFn_iff).2 hf) hdigits
  apply Finsupp.ext
  intro i
  exact congrFun (List.ofFn_inj.mp hlists) i

/-- Every coordinate of an exponent in the support is bounded by any bound
on the total degree. -/
theorem exponent_le_of_mem_support {p : MvPolynomial (Fin n) R}
    (hdegree : p.totalDegree ≤ d) {e : Fin n →₀ ℕ}
    (he : e ∈ p.support) (i : Fin n) :
    e i ≤ d :=
  (MvPolynomial.monomial_le_degreeOf i he).trans
    ((MvPolynomial.degreeOf_le_totalDegree p i).trans hdegree)

/-- On the support of a polynomial of total degree at most `d`, the weighted
exponent is injective as soon as `d < base`.

The `d = 0`, `base = 1` corner is handled separately because uniqueness of
ordinary base expansions is stated for bases greater than one. -/
theorem weightedExponent_injOn_support_of_totalDegree_le
    {p : MvPolynomial (Fin n) R}
    (hdegree : p.totalDegree ≤ d) (hbase : d < base) :
    Set.InjOn (weightedExponent base) (↑p.support : Set (Fin n →₀ ℕ)) := by
  intro e he f hf hcode
  have he' : e ∈ p.support := he
  have hf' : f ∈ p.support := hf
  cases d with
  | zero =>
      apply Finsupp.ext
      intro i
      have hei : e i = 0 :=
        Nat.eq_zero_of_le_zero
          (exponent_le_of_mem_support (d := 0) hdegree he' i)
      have hfi : f i = 0 :=
        Nat.eq_zero_of_le_zero
          (exponent_le_of_mem_support (d := 0) hdegree hf' i)
      rw [hei, hfi]
  | succ d =>
      apply weightedExponent_injective_of_lt_base
      · exact lt_of_le_of_lt (Nat.succ_le_succ (Nat.zero_le d)) hbase
      · intro i
        exact lt_of_le_of_lt
          (exponent_le_of_mem_support hdegree he' i) hbase
      · intro i
        exact lt_of_le_of_lt
          (exponent_le_of_mem_support hdegree hf' i) hbase
      · exact hcode

/-- The bounded Kronecker substitution ring homomorphism
`X i ↦ X ^ (base ^ i)`. -/
noncomputable def kroneckerSubstitution (base : ℕ) :
    MvPolynomial (Fin n) R →+* R[X] :=
  MvPolynomial.eval₂Hom Polynomial.C
    (fun i => Polynomial.X ^ (base ^ (i : ℕ)))

@[simp]
theorem kroneckerSubstitution_C (base : ℕ) (a : R) :
    kroneckerSubstitution (R := R) (n := n) base (MvPolynomial.C a) =
      Polynomial.C a := by
  simp [kroneckerSubstitution]

@[simp]
theorem kroneckerSubstitution_X (base : ℕ) (i : Fin n) :
    kroneckerSubstitution (R := R) base (MvPolynomial.X i) =
      Polynomial.X ^ (base ^ (i : ℕ)) := by
  simp [kroneckerSubstitution]

/-- A multivariate monomial is sent to the univariate monomial at its
weighted exponent. -/
theorem kroneckerSubstitution_monomial (base : ℕ)
    (e : Fin n →₀ ℕ) (a : R) :
    kroneckerSubstitution (R := R) base (MvPolynomial.monomial e a) =
      Polynomial.C a * Polynomial.X ^ weightedExponent base e := by
  change
    MvPolynomial.eval₂Hom Polynomial.C
        (fun i : Fin n => Polynomial.X ^ (base ^ (i : ℕ)))
        (MvPolynomial.monomial e a) = _
  rw [MvPolynomial.eval₂Hom_monomial, Finsupp.prod_pow]
  congr 1
  calc
    ∏ i : Fin n, (Polynomial.X ^ (base ^ (i : ℕ))) ^ e i =
        ∏ i : Fin n, Polynomial.X ^ (base ^ (i : ℕ) * e i) := by
      apply Finset.prod_congr rfl
      intro i _
      rw [← pow_mul]
    _ = Polynomial.X ^ weightedExponent base e := by
      simpa only [weightedExponent_apply] using
        (Finset.prod_pow_eq_pow_sum Finset.univ
          (fun i : Fin n => base ^ (i : ℕ) * e i)
          (Polynomial.X : R[X]))

/-- Expansion of Kronecker substitution as a finite sum of univariate
monomials. -/
theorem kroneckerSubstitution_eq_sum (base : ℕ)
    (p : MvPolynomial (Fin n) R) :
    kroneckerSubstitution (R := R) base p =
      ∑ e ∈ p.support,
        Polynomial.monomial (weightedExponent base e) (p.coeff e) := by
  conv_lhs => rw [p.as_sum]
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro e _
  rw [kroneckerSubstitution_monomial,
    Polynomial.C_mul_X_pow_eq_monomial]

/-- If weighted exponents are injective on the support, the coefficient at
the encoded exponent is the original multivariate coefficient. -/
theorem coeff_kroneckerSubstitution_of_mem_support
    (base : ℕ) (p : MvPolynomial (Fin n) R)
    (hinj : Set.InjOn (weightedExponent base)
      (↑p.support : Set (Fin n →₀ ℕ)))
    {e : Fin n →₀ ℕ} (he : e ∈ p.support) :
    (kroneckerSubstitution (R := R) base p).coeff
        (weightedExponent base e) = p.coeff e := by
  rw [kroneckerSubstitution_eq_sum, Polynomial.finsetSum_coeff,
    Finset.sum_eq_single e]
  · simp
  · intro f hf hfe
    rw [Polynomial.coeff_monomial, if_neg]
    intro hcode
    exact hfe (hinj hf he hcode)
  · intro hnot
    exact (hnot he).elim

/-- A coefficient outside the image of the original support is zero.  This
direction does not require injectivity. -/
theorem coeff_kroneckerSubstitution_eq_zero_of_notMem_image
    (base : ℕ) (p : MvPolynomial (Fin n) R) {k : ℕ}
    (hk : k ∉ p.support.image (weightedExponent base)) :
    (kroneckerSubstitution (R := R) base p).coeff k = 0 := by
  rw [kroneckerSubstitution_eq_sum, Polynomial.finsetSum_coeff]
  apply Finset.sum_eq_zero
  intro e he
  rw [Polynomial.coeff_monomial, if_neg]
  intro hcode
  apply hk
  exact Finset.mem_image.mpr ⟨e, he, hcode⟩

/-- With no collisions on the source support, Kronecker substitution maps
that support bijectively to its image. -/
theorem support_kroneckerSubstitution_eq_image
    (base : ℕ) (p : MvPolynomial (Fin n) R)
    (hinj : Set.InjOn (weightedExponent base)
      (↑p.support : Set (Fin n →₀ ℕ))) :
    (kroneckerSubstitution (R := R) base p).support =
      p.support.image (weightedExponent base) := by
  ext k
  constructor
  · intro hk
    have hkne : (kroneckerSubstitution (R := R) base p).coeff k ≠ 0 :=
      Polynomial.mem_support_iff.mp hk
    by_contra hnot
    exact hkne
      (coeff_kroneckerSubstitution_eq_zero_of_notMem_image base p hnot)
  · intro hk
    obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp hk
    apply Polynomial.mem_support_iff.mpr
    rw [coeff_kroneckerSubstitution_of_mem_support base p hinj he]
    exact MvPolynomial.mem_support_iff.mp he

/-- Collision-free Kronecker substitution preserves the finset of nonzero
coefficients. -/
theorem coeffs_kroneckerSubstitution_eq
    (base : ℕ) (p : MvPolynomial (Fin n) R)
    (hinj : Set.InjOn (weightedExponent base)
      (↑p.support : Set (Fin n →₀ ℕ))) :
    (kroneckerSubstitution (R := R) base p).coeffs = p.coeffs := by
  classical
  ext a
  rw [Polynomial.mem_coeffs_iff, MvPolynomial.mem_coeffs_iff]
  constructor
  · rintro ⟨k, hk, rfl⟩
    rw [support_kroneckerSubstitution_eq_image base p hinj] at hk
    obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp hk
    exact ⟨e, he, coeff_kroneckerSubstitution_of_mem_support base p hinj he⟩
  · rintro ⟨e, he, rfl⟩
    refine ⟨weightedExponent base e, ?_, ?_⟩
    · rw [support_kroneckerSubstitution_eq_image base p hinj]
      exact Finset.mem_image.mpr ⟨e, he, rfl⟩
    · exact
        (coeff_kroneckerSubstitution_of_mem_support base p hinj he).symm

/-- The coefficient-finset preservation theorem in the degree-bounded form
needed by the Hentzelt--Noether bridge. -/
theorem coeffs_kroneckerSubstitution_eq_of_totalDegree_le
    (base d : ℕ) (p : MvPolynomial (Fin n) R)
    (hdegree : p.totalDegree ≤ d) (hbase : d < base) :
    (kroneckerSubstitution (R := R) base p).coeffs = p.coeffs := by
  apply coeffs_kroneckerSubstitution_eq
  exact weightedExponent_injOn_support_of_totalDegree_le
    (p := p) (base := base) hdegree hbase

end Kronecker

section MultivariateCoefficientModules

variable {A R σ : Type*} [CommRing A] [CommRing R] [Algebra A R]

/-- The module over the base ring generated by the coefficients of a
multivariate polynomial. For `A = ℤ`, this is the module of integer-linear
combinations used in equation (17). -/
def mvCoefficientModule (p : MvPolynomial σ R) : Submodule A R :=
  Submodule.span A (p.coeffs : Set R)

/-- The multivariate coefficient-module form of Dedekind--Mertens cited in
Hentzelt--Noether equation (17). The proof uses a bounded Kronecker
substitution, so no global injectivity claim is made for that substitution. -/
theorem exists_dedekindMertens_mvCoefficientModule
    {n : ℕ} (f g : MvPolynomial (Fin n) R) :
    ∃ q : ℕ, 1 ≤ q ∧
      mvCoefficientModule (A := A) f ^ q *
          mvCoefficientModule (A := A) g =
        mvCoefficientModule (A := A) f ^ (q - 1) *
          mvCoefficientModule (A := A) (f * g) := by
  let base := f.totalDegree + g.totalDegree + 2
  let K := Kronecker.kroneckerSubstitution (R := R) (n := n) base
  let F : R[X] := K f
  let G : R[X] := K g
  have hsum_lt : f.totalDegree + g.totalDegree < base := by
    dsimp [base]
    omega
  have hf_lt : f.totalDegree < base :=
    lt_of_le_of_lt (Nat.le_add_right _ _) hsum_lt
  have hg_lt : g.totalDegree < base :=
    lt_of_le_of_lt (Nat.le_add_left _ _) hsum_lt
  have hcoeff_f : F.coeffs = f.coeffs := by
    simpa [F, K] using
      (Kronecker.coeffs_kroneckerSubstitution_eq_of_totalDegree_le
        (R := R) base f.totalDegree f le_rfl hf_lt)
  have hcoeff_g : G.coeffs = g.coeffs := by
    simpa [G, K] using
      (Kronecker.coeffs_kroneckerSubstitution_eq_of_totalDegree_le
        (R := R) base g.totalDegree g le_rfl hg_lt)
  have hdegree_mul : (f * g).totalDegree ≤
      f.totalDegree + g.totalDegree :=
    MvPolynomial.totalDegree_mul f g
  have hcoeff_mul : (K (f * g)).coeffs = (f * g).coeffs := by
    simpa [K] using
      (Kronecker.coeffs_kroneckerSubstitution_eq_of_totalDegree_le
        (R := R) base (f.totalDegree + g.totalDegree) (f * g)
          hdegree_mul hsum_lt)
  have hmap_mul : F * G = K (f * g) := by
    simp [F, G]
  have hcoeff_product : (F * G).coeffs = (f * g).coeffs := by
    rw [hmap_mul]
    exact hcoeff_mul
  have hmodule_f : coefficientModule (A := A) F =
      mvCoefficientModule (A := A) f := by
    rw [coefficientModule, mvCoefficientModule, hcoeff_f]
  have hmodule_g : coefficientModule (A := A) G =
      mvCoefficientModule (A := A) g := by
    rw [coefficientModule, mvCoefficientModule, hcoeff_g]
  have hmodule_product : coefficientModule (A := A) (F * G) =
      mvCoefficientModule (A := A) (f * g) := by
    rw [coefficientModule, mvCoefficientModule, hcoeff_product]
  have hdm := dedekindMertens_coefficientModule (A := A) F G
  rw [hmodule_f, hmodule_g, hmodule_product] at hdm
  refine ⟨G.natDegree + 1, Nat.succ_le_succ (Nat.zero_le _), ?_⟩
  simpa using hdm

end MultivariateCoefficientModules

variable {R : Type*} [CommRing R]

/-- Multiplication by a constant polynomial multiplies the content ideal by
the corresponding principal ideal. -/
theorem contentIdeal_mul_C_eq (f : R[X]) (b : R) :
    (f * C b).contentIdeal = f.contentIdeal * Ideal.span {b} := by
  apply le_antisymm
  · simpa using Polynomial.contentIdeal_mul_le_mul_contentIdeal f (C b)
  · change
      Ideal.span (f.coeffs : Set R) * Ideal.span ({b} : Set R) ≤
        (f * C b).contentIdeal
    rw [Ideal.span_mul_span, Ideal.span_le]
    rintro x ⟨a, ha, c, hc, rfl⟩
    simp only [Set.mem_singleton_iff] at hc
    subst c
    simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at ha
    obtain ⟨i, -, rfl⟩ := ha
    simpa [Polynomial.coeff_mul_C] using
      (f * C b).coeff_mem_contentIdeal i

/-- Removing one coefficient loses at most the principal ideal generated by
that coefficient. -/
theorem contentIdeal_le_erase_sup_span (g : R[X]) (m : ℕ) :
    g.contentIdeal ≤
      (g.erase m).contentIdeal ⊔ Ideal.span {g.coeff m} := by
  rw [Polynomial.contentIdeal_def, Ideal.span_le]
  intro x hx
  simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at hx
  obtain ⟨i, -, rfl⟩ := hx
  by_cases hi : i = m
  · subst i
    exact (show Ideal.span {g.coeff m} ≤
      (g.erase m).contentIdeal ⊔ Ideal.span {g.coeff m} from
        le_sup_right) (Ideal.subset_span (by simp))
  · apply (show (g.erase m).contentIdeal ≤
      (g.erase m).contentIdeal ⊔ Ideal.span {g.coeff m} from
        le_sup_left)
    have hmem := (g.erase m).coeff_mem_contentIdeal i
    simpa [Polynomial.coeff_erase, hi] using hmem

/-- The content of the product with one coefficient erased is controlled by
the original product content and the erased coefficient times `content f`. -/
theorem contentIdeal_mul_erase_le (f g : R[X]) (m : ℕ) :
    (f * g.erase m).contentIdeal ≤
      (f * g).contentIdeal ⊔
        f.contentIdeal * Ideal.span {g.coeff m} := by
  let t : R[X] := monomial m (g.coeff m)
  have hpoly : f * g.erase m + f * t = f * g := by
    rw [← mul_add]
    congr 1
    simpa [t, add_comm] using g.monomial_add_erase m
  rw [Polynomial.contentIdeal_def, Ideal.span_le]
  intro x hx
  simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at hx
  obtain ⟨k, -, rfl⟩ := hx
  have hcoeff := congrArg (fun p : R[X] => p.coeff k) hpoly
  simp only [Polynomial.coeff_add] at hcoeff
  have hleft : (f * g).coeff k ∈
      (f * g).contentIdeal ⊔
        f.contentIdeal * Ideal.span {g.coeff m} :=
    (show (f * g).contentIdeal ≤
      (f * g).contentIdeal ⊔
        f.contentIdeal * Ideal.span {g.coeff m} from le_sup_left)
      ((f * g).coeff_mem_contentIdeal k)
  have hterm0 :=
    Polynomial.contentIdeal_mul_le_mul_contentIdeal f t
      ((f * t).coeff_mem_contentIdeal k)
  have hterm : (f * t).coeff k ∈
      (f * g).contentIdeal ⊔
        f.contentIdeal * Ideal.span {g.coeff m} := by
    apply (show f.contentIdeal * Ideal.span {g.coeff m} ≤
      (f * g).contentIdeal ⊔
        f.contentIdeal * Ideal.span {g.coeff m} from le_sup_right)
    simpa [t] using hterm0
  rw [eq_sub_of_add_eq hcoeff]
  exact ((f * g).contentIdeal ⊔
    f.contentIdeal * Ideal.span {g.coeff m}).sub_mem hleft hterm

/-- The difficult containment in the univariate Dedekind--Mertens lemma,
stated for an arbitrary formal degree bound on the second polynomial. -/
theorem dedekindMertens_hard_bound (f g : R[X]) (m : ℕ)
    (hg : g.natDegree ≤ m) :
    f.contentIdeal ^ (m + 1) * g.contentIdeal ≤
      f.contentIdeal ^ m * (f * g).contentIdeal := by
  induction m generalizing g with
  | zero =>
      have hg0 : g.natDegree = 0 := Nat.eq_zero_of_le_zero hg
      rw [Polynomial.eq_C_of_natDegree_eq_zero hg0]
      simp [contentIdeal_mul_C_eq]
  | succ n ih =>
      let m := n + 1
      let F : Ideal R := f.contentIdeal
      let Q : Ideal R := (g.erase m).contentIdeal
      let b : R := g.coeff m
      let H : Ideal R := (f * g).contentIdeal
      let K : Ideal R := F ^ m * H
      have hm : m = n + 1 := rfl
      have hqdeg : (g.erase m).natDegree ≤ n := by
        rw [Polynomial.natDegree_le_iff_coeff_eq_zero]
        intro j hj
        rw [Polynomial.coeff_erase]
        split_ifs with heq
        · rfl
        · apply g.coeff_eq_zero_of_natDegree_lt
          have hmj : m < j := by
            have hmle : m ≤ j := by
              simpa [m] using (Nat.succ_le_iff.mpr hj)
            exact lt_of_le_of_ne hmle (fun h => heq h.symm)
          exact hg.trans_lt (by simpa [m] using hmj)
      have hrec : F ^ m * Q ≤
          F ^ n * (f * g.erase m).contentIdeal := by
        simpa [F, Q, m] using ih (g.erase m) hqdeg
      have herase : (f * g.erase m).contentIdeal ≤
          H ⊔ F * Ideal.span {b} := by
        simpa [F, H, b] using contentIdeal_mul_erase_le f g m

      let A : ℕ → Prop := fun i =>
        Ideal.span {f.coeff i} * (F ^ m * Q) ≤ K
      let B : ℕ → Prop := fun i =>
        Ideal.span {f.coeff i * b} * F ^ m ≤ K
      let Tail : ℕ → Prop := fun i =>
        ∀ j, i ≤ j → A j ∧ B j

      have htail_top : Tail (f.natDegree + 1) := by
        intro j hj
        have hzero : f.coeff j = 0 :=
          f.coeff_eq_zero_of_natDegree_lt
            ((Nat.lt_succ_self f.natDegree).trans_le hj)
        simp [A, B, hzero]

      have htail_step : ∀ i < f.natDegree + 1,
          Tail (i + 1) → Tail i := by
        intro i hi htail j hij
        by_cases hji : j = i
        · subst j
          have hB : B i := by
            change Ideal.span {f.coeff i * b} * F ^ m ≤ K
            rw [Ideal.span_singleton_mul_le_iff]
            intro u hu
            let S := (Finset.antidiagonal (i + m)).erase (i, m)
            have himem : (i, m) ∈ Finset.antidiagonal (i + m) := by
              simp
            have hconv : (f * g).coeff (i + m) =
                f.coeff i * b +
                  ∑ p ∈ S, f.coeff p.1 * g.coeff p.2 := by
              rw [Polynomial.coeff_mul,
                ← Finset.insert_erase himem,
                Finset.sum_insert (Finset.notMem_erase _ _)]
            have hmain : (f * g).coeff (i + m) * u ∈ K := by
              simpa [mul_comm] using Ideal.mul_mem_mul hu
                ((f * g).coeff_mem_contentIdeal (i + m))
            have hsum :
                (∑ p ∈ S, f.coeff p.1 * g.coeff p.2) * u ∈ K := by
              rw [Finset.sum_mul]
              apply K.sum_mem
              intro p hp
              rw [Finset.mem_erase, Finset.mem_antidiagonal] at hp
              rcases p with ⟨x, y⟩
              by_cases hym : m < y
              · have hgy : g.coeff y = 0 :=
                  g.coeff_eq_zero_of_natDegree_lt
                    (hg.trans_lt (by simpa [m] using hym))
                simp [hgy]
              · have hymle : y ≤ m := Nat.le_of_not_gt hym
                have hyne : y ≠ m := by
                  intro hy
                  apply hp.1
                  have hx : x = i := by
                    simpa [hy] using hp.2
                  simp [hx, hy]
                have hylt : y < m := lt_of_le_of_ne hymle hyne
                have hix : i < x := by
                  by_contra hix
                  have hbad : x + y < i + m :=
                    Nat.add_lt_add_of_le_of_lt (Nat.le_of_not_gt hix) hylt
                  rw [hp.2] at hbad
                  exact (Nat.lt_irrefl _ hbad)
                have hqcoeff : g.coeff y ∈ Q := by
                  have hmem := (g.erase m).coeff_mem_contentIdeal y
                  simpa [Q, Polynomial.coeff_erase, hyne] using hmem
                have hAx :=
                  (htail x (Nat.succ_le_iff.mpr hix)).1
                have hAx' := Ideal.span_singleton_mul_le_iff.mp hAx
                have huz : u * g.coeff y ∈ F ^ m * Q :=
                  Ideal.mul_mem_mul hu hqcoeff
                convert hAx' (u * g.coeff y) huz using 1; ring
            rw [hconv] at hmain
            convert K.sub_mem hmain hsum using 1; ring
          have hA : A i := by
            change Ideal.span {f.coeff i} * (F ^ m * Q) ≤ K
            rw [Ideal.span_singleton_mul_le_iff]
            intro z hz
            have hz' : z ∈ F ^ n * (f * g.erase m).contentIdeal := hrec hz
            have hmul : Ideal.span {f.coeff i} *
                (F ^ n * (f * g.erase m).contentIdeal) ≤ K := by
              calc
                Ideal.span {f.coeff i} *
                    (F ^ n * (f * g.erase m).contentIdeal)
                    ≤ Ideal.span {f.coeff i} *
                        (F ^ n * (H ⊔ F * Ideal.span {b})) :=
                  Ideal.mul_mono le_rfl
                    (Ideal.mul_mono le_rfl herase)
                _ = (Ideal.span {f.coeff i} * (F ^ n * H)) ⊔
                    (Ideal.span {f.coeff i} *
                      (F ^ n * (F * Ideal.span {b}))) := by
                  rw [Ideal.mul_sup, Ideal.mul_sup]
                _ ≤ K := by
                  apply sup_le
                  · calc
                      Ideal.span {f.coeff i} * (F ^ n * H)
                          = (Ideal.span {f.coeff i} * F ^ n) * H := by
                            rw [Ideal.mul_assoc]
                      _ ≤ (F * F ^ n) * H :=
                        Ideal.mul_mono
                          (Ideal.mul_mono
                            (Ideal.span_le.mpr
                              (Set.singleton_subset_iff.mpr
                                (f.coeff_mem_contentIdeal i))) le_rfl)
                          le_rfl
                      _ = K := by simp [K, hm, pow_succ']
                  · have hrew :
                        Ideal.span {f.coeff i} *
                            (F ^ n * (F * Ideal.span {b})) =
                          Ideal.span {f.coeff i * b} * F ^ m := by
                        rw [← Ideal.span_singleton_mul_span_singleton,
                          pow_succ']
                        ac_rfl
                    rw [hrew]
                    exact hB
            exact (Ideal.span_singleton_mul_le_iff.mp hmul) z hz'
          exact ⟨hA, hB⟩
        · have hijlt : i < j :=
            lt_of_le_of_ne hij (Ne.symm hji)
          exact htail j (Nat.succ_le_iff.mpr hijlt)

      have htail_zero : Tail 0 :=
        Nat.decreasingInduction
          (n := f.natDegree + 1)
          (fun i hi htail => htail_step i hi htail)
          htail_top (Nat.zero_le _)
      have hall (i : ℕ) : A i ∧ B i := htail_zero i (Nat.zero_le i)

      have hF_A : F ≤ K.colon (F ^ m * Q : Set R) := by
        change f.contentIdeal ≤ K.colon (F ^ m * Q : Set R)
        rw [Polynomial.contentIdeal_def, Ideal.span_le]
        intro x hx
        simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at hx
        obtain ⟨i, -, rfl⟩ := hx
        apply Submodule.mem_colon.mpr
        intro z hz
        have hAi := Ideal.span_singleton_mul_le_iff.mp (hall i).1
        simpa [smul_eq_mul] using hAi z hz
      have hQ : F * (F ^ m * Q) ≤ K := by
        apply Ideal.mul_le.2
        intro a ha z hz
        have ha' := Submodule.mem_colon.mp (hF_A ha) z hz
        simpa [smul_eq_mul] using ha'

      let L : Ideal R := K.colon (↑(F ^ m) : Set R)
      have hF_B : F ≤ L.colon (Ideal.span {b} : Set R) := by
        change f.contentIdeal ≤ L.colon (Ideal.span {b} : Set R)
        rw [Polynomial.contentIdeal_def, Ideal.span_le]
        intro x hx
        simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at hx
        obtain ⟨i, -, rfl⟩ := hx
        rw [Ideal.colon_span]
        apply Submodule.mem_colon.mpr
        intro y hy
        simp only [Set.mem_singleton_iff] at hy
        subst y
        change f.coeff i * b ∈ K.colon (↑(F ^ m) : Set R)
        apply Submodule.mem_colon.mpr
        intro u hu
        have hBi := Ideal.span_singleton_mul_le_iff.mp (hall i).2
        simpa [smul_eq_mul] using hBi u hu
      have hFb : F * Ideal.span {b} ≤ L := by
        apply Ideal.mul_le.2
        intro a ha y hy
        have ha' := Submodule.mem_colon.mp (hF_B ha) y hy
        simpa [smul_eq_mul] using ha'
      have hb : (F * Ideal.span {b}) * F ^ m ≤ K := by
        apply Ideal.mul_le.2
        intro x hx u hu
        have hx' := Submodule.mem_colon.mp (hFb hx) u hu
        simpa [L, smul_eq_mul] using hx'

      have hG : g.contentIdeal ≤ Q ⊔ Ideal.span {b} := by
        simpa [Q, b] using contentIdeal_le_erase_sup_span g m
      calc
        f.contentIdeal ^ (n + 1 + 1) * g.contentIdeal
            ≤ F ^ (m + 1) * (Q ⊔ Ideal.span {b}) := by
              simpa [F, m] using Ideal.mul_mono le_rfl hG
        _ = (F ^ (m + 1) * Q) ⊔
              (F ^ (m + 1) * Ideal.span {b}) := by
              rw [Ideal.mul_sup]
        _ ≤ K := by
          apply sup_le
          · simpa [pow_succ', Ideal.mul_assoc] using hQ
          · have hrew : F ^ (m + 1) * Ideal.span {b} =
                (F * Ideal.span {b}) * F ^ m := by
              rw [pow_succ']
              ac_rfl
            rw [hrew]
            exact hb
        _ = f.contentIdeal ^ (n + 1) * (f * g).contentIdeal := by
          simp [K, F, H, m]

/-- Unrestricted univariate Dedekind--Mertens over an arbitrary commutative
ring, with the sharp exponent determined by the natural degree of `g`. -/
theorem dedekindMertens (f g : R[X]) :
    f.contentIdeal ^ (g.natDegree + 1) * g.contentIdeal =
      f.contentIdeal ^ g.natDegree * (f * g).contentIdeal := by
  apply le_antisymm
  · exact dedekindMertens_hard_bound f g g.natDegree le_rfl
  · calc
      f.contentIdeal ^ g.natDegree * (f * g).contentIdeal
          ≤ f.contentIdeal ^ g.natDegree *
              (f.contentIdeal * g.contentIdeal) :=
        Ideal.mul_mono le_rfl
          (Polynomial.contentIdeal_mul_le_mul_contentIdeal f g)
      _ = f.contentIdeal ^ (g.natDegree + 1) * g.contentIdeal := by
        rw [pow_succ]
        ac_rfl

/-- The content ideal of an explicitly linear polynomial is generated by its
constant and linear coefficients. -/
theorem contentIdeal_C_add_C_mul_X (b₀ b₁ : R) :
    (C b₀ + C b₁ * X).contentIdeal = Ideal.span {b₀, b₁} := by
  apply le_antisymm
  · rw [Polynomial.contentIdeal_def, Ideal.span_le]
    intro x hx
    simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at hx
    obtain ⟨n, -, rfl⟩ := hx
    have hb₀ : b₀ ∈ Ideal.span ({b₀, b₁} : Set R) :=
      Ideal.subset_span (by simp)
    have hb₁ : b₁ ∈ Ideal.span ({b₀, b₁} : Set R) :=
      Ideal.subset_span (by simp)
    rcases n with _ | n
    · simpa using hb₀
    · rcases n with _ | n
      · simpa using hb₁
      · simp
  · rw [Ideal.span_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    have hcoeff_zero : (C b₀ + C b₁ * X).coeff 0 = b₀ := by
      rw [coeff_add, coeff_mul_X_zero]
      simp
    have hcoeff_one : (C b₀ + C b₁ * X).coeff 1 = b₁ := by
      rw [coeff_add, coeff_mul_X]
      simp
    have hmem_zero := (C b₀ + C b₁ * X).coeff_mem_contentIdeal 0
    have hmem_one := (C b₀ + C b₁ * X).coeff_mem_contentIdeal 1
    rw [hcoeff_zero] at hmem_zero
    rw [hcoeff_one] at hmem_one
    rcases hx with hx | hx
    · rw [hx]
      exact hmem_zero
    · rw [hx]
      exact hmem_one

/-- The hard containment in Dedekind--Mertens when the second polynomial has
degree at most one. The proof is the coefficient recurrence itself. -/
theorem contentIdeal_sq_mul_span_pair_le_mul_contentIdeal
    (f : R[X]) (b₀ b₁ : R) :
    f.contentIdeal ^ 2 * Ideal.span {b₀, b₁} ≤
      f.contentIdeal * (f * (C b₀ + C b₁ * X)).contentIdeal := by
  let g : R[X] := C b₀ + C b₁ * X
  let K : Ideal R := f.contentIdeal * (f * g).contentIdeal
  have hcoeff_zero : (f * g).coeff 0 = f.coeff 0 * b₀ := by
    simp [g, mul_add]
  have hcoeff_succ (n : ℕ) :
      (f * g).coeff (n + 1) =
        f.coeff (n + 1) * b₀ + f.coeff n * b₁ := by
    change (f * (C b₀ + C b₁ * X)).coeff (n + 1) = _
    rw [mul_add, coeff_add, coeff_mul_C, ← mul_assoc, coeff_mul_X,
      coeff_mul_C]
  have hprod (i k : ℕ) : f.coeff i * (f * g).coeff k ∈ K := by
    exact Ideal.mul_mem_mul (f.coeff_mem_contentIdeal i)
      ((f * g).coeff_mem_contentIdeal k)
  have hb₁ : ∀ i j : ℕ, f.coeff i * f.coeff j * b₁ ∈ K := by
    intro i
    induction i with
    | zero =>
        intro j
        have hleft := hprod 0 (j + 1)
        have hright := hprod (j + 1) 0
        rw [hcoeff_succ j] at hleft
        rw [hcoeff_zero] at hright
        convert K.sub_mem hleft hright using 1
        all_goals ring
    | succ i ih =>
        intro j
        have hleft := hprod (i + 1) (j + 1)
        have hright := hprod (j + 1) (i + 1)
        rw [hcoeff_succ j] at hleft
        rw [hcoeff_succ i] at hright
        have h := K.add_mem (K.sub_mem hleft hright) (ih (j + 1))
        convert h using 1
        all_goals ring
  have hb₀ : ∀ i j : ℕ, f.coeff i * f.coeff j * b₀ ∈ K := by
    intro i j
    rcases j with _ | j
    · have h := hprod i 0
      rw [hcoeff_zero] at h
      convert h using 1
      all_goals ring
    · have hleft := hprod i (j + 1)
      rw [hcoeff_succ j] at hleft
      convert K.sub_mem hleft (hb₁ i j) using 1
      all_goals ring
  change
    (Ideal.span (f.coeffs : Set R)) ^ 2 * Ideal.span {b₀, b₁} ≤ _
  rw [pow_two, Ideal.span_mul_span, Ideal.span_mul_span, Ideal.span_le]
  intro x hx
  rcases hx with ⟨ab, hab, b, hb, rfl⟩
  rcases hab with ⟨a, ha, a', ha', rfl⟩
  simp only [Finset.mem_coe, Polynomial.mem_coeffs_iff] at ha ha'
  obtain ⟨i, -, rfl⟩ := ha
  obtain ⟨j, -, rfl⟩ := ha'
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hb
  rcases hb with rfl | rfl
  · simpa [K, g, mul_assoc] using hb₀ i j
  · simpa [K, g, mul_assoc] using hb₁ i j

/-- The formal easy direction in Dedekind--Mertens. -/
theorem mul_le_sq_mul_of_le_mul {I J K : Ideal R} (h : K ≤ I * J) :
    I * K ≤ I ^ 2 * J := by
  calc
    I * K ≤ I * (I * J) := mul_le_mul' le_rfl h
    _ = I ^ 2 * J := by rw [pow_two, Ideal.mul_assoc]

/-- Dedekind--Mertens for an explicitly linear second factor. -/
theorem dedekindMertens_linear (f : R[X]) (b₀ b₁ : R) :
    f.contentIdeal ^ 2 * (C b₀ + C b₁ * X).contentIdeal =
      f.contentIdeal * (f * (C b₀ + C b₁ * X)).contentIdeal := by
  apply le_antisymm
  · rw [contentIdeal_C_add_C_mul_X]
    exact contentIdeal_sq_mul_span_pair_le_mul_contentIdeal f b₀ b₁
  · exact mul_le_sq_mul_of_le_mul
      (Polynomial.contentIdeal_mul_le_mul_contentIdeal _ _)

/-- Every polynomial of natural degree at most one is its constant coefficient
plus its linear coefficient times `X`. -/
theorem eq_C_add_C_mul_X_of_natDegree_le_one (g : R[X])
    (hg : g.natDegree ≤ 1) :
    g = C (g.coeff 0) + C (g.coeff 1) * X := by
  ext n
  cases n with
  | zero => simp
  | succ n =>
      cases n with
      | zero => simp
      | succ n =>
          have hzero : g.coeff (n + 2) = 0 :=
            g.coeff_eq_zero_of_natDegree_lt
              (hg.trans_lt (Nat.succ_lt_succ (Nat.zero_lt_succ n)))
          simpa [coeff_add, coeff_C_mul] using hzero

/-- The sharp degree-one Dedekind--Mertens identity over an arbitrary
commutative ring. -/
theorem dedekindMertens_of_natDegree_le_one (f g : R[X])
    (hg : g.natDegree ≤ 1) :
    f.contentIdeal ^ 2 * g.contentIdeal =
      f.contentIdeal * (f * g).contentIdeal := by
  rw [eq_C_add_C_mul_X_of_natDegree_le_one g hg]
  exact dedekindMertens_linear f (g.coeff 0) (g.coeff 1)

/-- Existential-exponent form of the linear case, matching equation (17) in
Hentzelt--Noether Satz VI. -/
theorem exists_dedekindMertens_exponent_linear (f : R[X]) (b₀ b₁ : R) :
    ∃ q : ℕ, 1 ≤ q ∧
      f.contentIdeal ^ q * (C b₀ + C b₁ * X).contentIdeal =
        f.contentIdeal ^ (q - 1) *
          (f * (C b₀ + C b₁ * X)).contentIdeal := by
  refine ⟨2, by decide, ?_⟩
  simpa using dedekindMertens_linear f b₀ b₁

/-- The two principal ideals have the same radical when one generator divides
the other and the latter divides a power of the former. In Satz VIII, `e` is
the elementary-divisor form and `r` is the resultant form. -/
theorem radical_span_eq_of_dvd_pow
    {R : Type*} [CommRing R] {e r : R}
    (he : e ∣ r) (n : ℕ) (hr : r ∣ e ^ n) :
    (Ideal.span {r}).radical = (Ideal.span {e}).radical := by
  apply le_antisymm
  · exact Ideal.radical_mono <|
      Ideal.span_singleton_le_span_singleton.mpr he
  · have he_mem : e ∈ (Ideal.span {r}).radical :=
      ⟨n, Ideal.mem_span_singleton.mpr hr⟩
    have hspan : Ideal.span {e} ≤ (Ideal.span {r}).radical :=
      Ideal.span_le.mpr <| Set.singleton_subset_iff.mpr he_mem
    simpa using Ideal.radical_mono hspan

/-- Mutual divisibility up to a power forces two elements to vanish together
after every map to a field. This is the abstract algebraic core of the
zero-set consequence of Hentzelt--Noether Satz VIII. -/
theorem map_eq_zero_iff_of_dvd_pow
    {R K : Type*} [CommRing R] [Field K]
    (φ : R →+* K) {e r : R} (he : e ∣ r) (n : ℕ) (hr : r ∣ e ^ n) :
    φ r = 0 ↔ φ e = 0 := by
  constructor
  · intro hφr
    obtain ⟨c, hc⟩ := hr
    have hpow : φ e ^ n = 0 := by
      rw [← map_pow, hc, map_mul, hφr, zero_mul]
    by_contra hφe
    exact (pow_ne_zero n hφe) hpow
  · intro hφe
    obtain ⟨c, hc⟩ := he
    rw [hc, map_mul, hφe, zero_mul]

/-- Polynomial-evaluation form of `map_eq_zero_iff_of_dvd_pow`. -/
theorem aeval_eq_zero_iff_of_dvd_pow
    {P K σ : Type*} [Field P] [Field K] [Algebra P K]
    (x : σ → K) {e r : MvPolynomial σ P}
    (he : e ∣ r) (n : ℕ) (hr : r ∣ e ^ n) :
    MvPolynomial.aeval x r = 0 ↔ MvPolynomial.aeval x e = 0 :=
  map_eq_zero_iff_of_dvd_pow (MvPolynomial.aeval x).toRingHom he n hr

/-- The resultant form and elementary-divisor form have the same pointwise
vanishing set whenever the two divisibility conclusions of Satz VIII hold. -/
theorem vanishingSet_eq_of_dvd_pow
    {P K σ : Type*} [Field P] [Field K] [Algebra P K]
    {e r : MvPolynomial σ P} (he : e ∣ r) (n : ℕ) (hr : r ∣ e ^ n) :
    {x : σ → K | MvPolynomial.aeval x r = 0} =
      {x : σ → K | MvPolynomial.aeval x e = 0} := by
  ext x
  exact aeval_eq_zero_iff_of_dvd_pow x he n hr

#print axioms coefficientModule
#print axioms coefficientModule_self_eq_contentIdeal
#print axioms coeff_mem_coefficientModule
#print axioms coefficientModule_monomial
#print axioms coefficientModule_C
#print axioms coefficientModule_mul_le_mul_coefficientModule
#print axioms coefficientModule_mul_C_eq
#print axioms coefficientModule_le_erase_sup_span
#print axioms coefficientModule_mul_erase_le
#print axioms span_singleton_mul_le_iff
#print axioms coefficientModule_mul_le_of_coefficients
#print axioms dedekindMertens_coefficientModule_hard_bound
#print axioms dedekindMertens_coefficientModule
#print axioms dedekindMertens_module_le_restrictScalars
#print axioms mvPolynomial_coeff_pow_mem_submodule_pow
#print axioms mvPolynomial_pow_mul_C_mem_coefficientExtension
#print axioms Kronecker.weightedExponent
#print axioms Kronecker.weightedExponent_apply
#print axioms Kronecker.weightedExponent_single
#print axioms Kronecker.ofDigits_ofFn_eq_weightedExponent
#print axioms Kronecker.weightedExponent_injective_of_lt_base
#print axioms Kronecker.exponent_le_of_mem_support
#print axioms Kronecker.weightedExponent_injOn_support_of_totalDegree_le
#print axioms Kronecker.kroneckerSubstitution
#print axioms Kronecker.kroneckerSubstitution_C
#print axioms Kronecker.kroneckerSubstitution_X
#print axioms Kronecker.kroneckerSubstitution_monomial
#print axioms Kronecker.kroneckerSubstitution_eq_sum
#print axioms Kronecker.coeff_kroneckerSubstitution_of_mem_support
#print axioms Kronecker.coeff_kroneckerSubstitution_eq_zero_of_notMem_image
#print axioms Kronecker.support_kroneckerSubstitution_eq_image
#print axioms Kronecker.coeffs_kroneckerSubstitution_eq
#print axioms Kronecker.coeffs_kroneckerSubstitution_eq_of_totalDegree_le
#print axioms mvCoefficientModule
#print axioms exists_dedekindMertens_mvCoefficientModule
#print axioms radical_span_eq_of_dvd_pow
#print axioms map_eq_zero_iff_of_dvd_pow
#print axioms aeval_eq_zero_iff_of_dvd_pow
#print axioms vanishingSet_eq_of_dvd_pow
#print axioms contentIdeal_mul_C_eq
#print axioms contentIdeal_le_erase_sup_span
#print axioms contentIdeal_mul_erase_le
#print axioms dedekindMertens_hard_bound
#print axioms dedekindMertens
#print axioms contentIdeal_C_add_C_mul_X
#print axioms contentIdeal_sq_mul_span_pair_le_mul_contentIdeal
#print axioms mul_le_sq_mul_of_le_mul
#print axioms dedekindMertens_linear
#print axioms eq_C_add_C_mul_X_of_natDegree_le_one
#print axioms dedekindMertens_of_natDegree_le_one
#print axioms exists_dedekindMertens_exponent_linear

end MathematicalCommons.Noether.PolynomialIdealsAndResultants1923
